function precompute_cifti_neighbors(outfile)
% precompute_cifti_neighbors
%   Builds a grayordinate-level neighbor list for HCP-style dense CIFTI
%   (32k surfaces + subcortex/brainstem/cerebellum volume) and saves it
%   to a MAT file for fast TFCE/Cluster-Extent operations.
%
%   Usage:
%       precompute_cifti_neighbors();
%       precompute_cifti_neighbors('cifti_neighbors_all.mat');
%
%   Output MAT contains:
%       - neighbors: cell(91282,1), neighbors{i} are grayordinate neighbors of i
%       - meta: struct with fields .version, .date, .notes
%
%   Requirements:
%       - cifti_brainmodel.mat must be on the MATLAB path (generated by
%         general_create_cifti_mat.m). It must contain variables 'cifti'
%         (with cortex adjacency and volume indices) and 'components'
%         (with .volumeMask).

    if nargin < 1 || isempty(outfile)
        outfile = 'cifti_neighbors_all.mat';
    end

    fprintf('\n---> Loading cifti_brainmodel ...');
    S = load('cifti_brainmodel');
    cifti = S.cifti;
    components = S.components;
    fprintf(' done.');

    % Initialize
    totalGray = 91282; % standard 32k LR dense grayordinates
    neighbors = cell(totalGray,1);

    % Helper: find index for cortex components
    idxL = find(strcmp(cifti.shortnames, 'cortex_left'), 1);
    idxR = find(strcmp(cifti.shortnames, 'cortex_right'), 1);
    if isempty(idxL) || isempty(idxR)
        error('precompute_cifti_neighbors: cortex_left/right not found in cifti.shortnames.');
    end

    % Cortex Left
    fprintf('\n---> Building cortex-left neighbors ...');
    left_gidx = cifti.start(idxL):cifti.end(idxL);
    left_mask_pos = find(cifti.cortex_left.mask);
    inv_left = zeros(max(left_mask_pos),1);
    inv_left(left_mask_pos) = 1:numel(left_mask_pos);
    for ii = 1:numel(left_gidx)
        vtx = left_mask_pos(ii);
        neigh_vtx = cifti.cortex_left.adj_list.neighbours{vtx};
        neigh_vtx = neigh_vtx(neigh_vtx > 0 & neigh_vtx <= numel(inv_left));
        pos = inv_left(neigh_vtx);
        pos = pos(pos>0 & pos<=numel(left_gidx));
        neighbors{left_gidx(ii)} = left_gidx(pos(:)');
    end
    fprintf(' done.');

    % Cortex Right
    fprintf('\n---> Building cortex-right neighbors ...');
    right_gidx = cifti.start(idxR):cifti.end(idxR);
    right_mask_pos = find(cifti.cortex_right.mask);
    inv_right = zeros(max(right_mask_pos),1);
    inv_right(right_mask_pos) = 1:numel(right_mask_pos);
    for ii = 1:numel(right_gidx)
        vtx = right_mask_pos(ii);
        neigh_vtx = cifti.cortex_right.adj_list.neighbours{vtx};
        neigh_vtx = neigh_vtx(neigh_vtx > 0 & neigh_vtx <= numel(inv_right));
        pos = inv_right(neigh_vtx);
        pos = pos(pos>0 & pos<=numel(right_gidx));
        neighbors{right_gidx(ii)} = right_gidx(pos(:)');
    end
    fprintf(' done.');

    % Subcortex/Volume neighbors (26-connectivity)
    fprintf('\n---> Building subcortex/volume neighbors (26-connectivity) ...');

    volSize = size(components.volumeMask);
    volGray = zeros(volSize, 'uint32'); % grayordinate index per voxel

    % Build grayordinate mapping for volume components
    for i = 1:numel(cifti.shortnames)
        name = cifti.shortnames{i};
        if ~isfield(cifti, name), continue; end
        if ~isfield(cifti.(name), 'type'), continue; end
        if ~strcmp(cifti.(name).type, 'Volume'), continue; end
        A = cifti.(name).indices; % [N x 3], 0-based indices
        if isempty(A), continue; end
        start_idx = cifti.start(i);
        for j = 1:size(A,1)
            x = A(j,1)+1; y = A(j,2)+1; z = A(j,3)+1;
            volGray(x,y,z) = uint32(start_idx + (j-1));
        end
    end

    % 26-neighborhood offsets
    offs = int32([]);
    idx = 0;
    for dx=-1:1
        for dy=-1:1
            for dz=-1:1
                if dx==0 && dy==0 && dz==0, continue; end
                idx = idx + 1;
                offs(idx,:) = [dx dy dz]; %#ok<AGROW>
            end
        end
    end

    % Iterate volume voxels and assign neighbor grayordinates
    [X,Y,Z] = ind2sub(volSize, find(volGray>0));
    for ii = 1:numel(X)
        x = X(ii); y = Y(ii); z = Z(ii);
        go = volGray(x,y,z);
        ng = [];
        for o = 1:size(offs,1)
            xx = x + offs(o,1); yy = y + offs(o,2); zz = z + offs(o,3);
            if xx<1 || yy<1 || zz<1 || xx>volSize(1) || yy>volSize(2) || zz>volSize(3)
                continue;
            end
            go2 = volGray(xx,yy,zz);
            if go2>0
                ng(end+1) = double(go2); %#ok<AGROW>
            end
        end
        if ~isempty(ng)
            neighbors{double(go)} = unique(ng);
        end
    end
    fprintf(' done.');

    % Save
    meta = struct('version','1.0', 'date', datestr(now, 'yyyy-mm-dd HH:MM:SS'), ...
                  'notes','CIFTI cortex one-ring and subcortical 26-connectivity');
    fprintf('\n---> Saving neighbors to %s ...', outfile);
    % Save in MATLAB v7 format for cross-compatibility (MATLAB & Octave)
    try
        save(outfile, 'neighbors', 'meta', '-v7');
    catch
        % Fallback: default save without version flag
        save(outfile, 'neighbors', 'meta');
    end
    fprintf(' done.\n');
end
