#!/usr/bin/env python
# encoding: utf-8

# SPDX-FileCopyrightText: 2021 QuNex development team <https://qunex.yale.edu/>
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""
``core.py``

This file holds code for core support functions used by other code for
preprocessing and analysis. The functions are for internal use
and can not be called externally.
"""

import gzip
import inspect
import re
import os.path
import multiprocessing
import os
import os.path
import shutil
import subprocess
import sys
import time
import traceback
import types
from concurrent.futures import ProcessPoolExecutor
from datetime import datetime

import qx_utilities.general.batch_io as bio
import qx_utilities.general.filelock as fl
import qx_utilities.general.exceptions as ge

# the batch file parser, the session selector and the filter live in batch_io,
# which imports nothing from QuNex so it can be spliced into qunex_container.
# re-exported here, as this is where the tree imports them from.
BatchError = bio.BatchError
SessionList = bio.SessionList
read_batch = bio.read_batch
read_list = bio.read_list


def print_qunex_header(timestamp=None, file=None):
    """
    ``print_qunex_header(timestamp=None, file=None)``

    Prepares and returns a standard "Generated by QuNex" string. If file
    is not None, it prints it to the specified file. If timestamp is not
    none, it uses the specified timestamp, which can be either a string
    or a datetime object.
    """
    if timestamp is None:
        timestamp = datetime.now().strftime("%Y-%m-%d_%H.%M.%S.%f")
    elif type(timestamp) is datetime:
        timestamp = timestamp.strftime("%Y-%m-%d_%H.%M.%S.%f")

    header = f"# Generated by QuNex {get_qunex_version()} on {timestamp}"
    if file:
        print(header, file=file)

    return header


# ==============================================================================
#                                              SESSION AND SUBJECT LIST HANDLING

# The parsing, selection and filtering themselves live in `batch_io`, which
# imports nothing from QuNex. What is added here is the QuNex error types.


def resolve_sessions(
    batchfile=None,
    sessions=None,
    filter=None,
    sessionsfolder=None,
    command=None,
    verbose=False,
):
    """
    ``resolve_sessions(batchfile=None, sessions=None, filter=None, sessionsfolder=None, command=None, verbose=False)``

    The single entry point for "which batch file, which sessions". Returns a
    tuple of the SessionList of the selected sessions and the parameters
    specified in the batch file header.

    If batchfile is provided, it is parsed - as a `*.list` file if it has that
    extension, as a batch file otherwise - and sessions and filter select within
    it. A batch file that is absent or can not be read is always an error.

    If batchfile is not provided, sessions is a comma, space or pipe separated
    list of session ids or globs, matched against the folders in sessionsfolder
    if one is given and taken as plain ids if it is not. The returned header
    parameters are then empty.

    If the command is running as a SLURM job array, only the sessions that
    belong to this array task are returned.
    """

    records = []
    header = {}

    try:
        if batchfile and batchfile.strip():
            batchfile = batchfile.strip()
            if re.match(r".*\.list$", batchfile):
                records = bio.read_list(batchfile, verbose=verbose)
            else:
                records, header = bio.read_batch(batchfile, verbose=verbose)

        # a `*.list` file is a session specification, so it can also arrive
        # through sessions: it is the source of the sessions when there is no
        # batch file, and selects within one when there is
        if sessions and re.match(r"^\s*\S+\.list\s*$", sessions):
            list_records = bio.read_list(sessions.strip(), verbose=verbose)
            if records:
                sessions = ",".join([e["id"] for e in list_records if "id" in e])
            else:
                records, sessions = list_records, None

        slist = bio.select_sessions(
            records, sessions=sessions, filter=filter, sessionsfolder=sessionsfolder
        )

    except bio.BatchError as e:
        raise ge.CommandFailed(
            command if command else "resolve_sessions",
            "Could not compile the list of sessions to process",
            str(e),
            "Please check your parameters!",
        )

    # are we inside a SLURM job array?
    if "SLURM_ARRAY_TASK_ID" in os.environ:
        # get ID for this job
        slurm_array_ix = int(os.environ["SLURM_ARRAY_TASK_ID"])

        # get size of job array
        slurm_array_size = int(os.environ["SLURM_ARRAY_TASK_MAX"]) + 1

        # get the chunk
        slist = slist[slurm_array_ix::slurm_array_size]

    return slist, header


# ==============================================================================
#                                                          EXECUTION AND LOGGING

def deduce_folders(args, command=None, timestamp=None):
    """
    ``deduce_folders(args)``

    Tries to deduce the location of study specific folders based on the provided
    arguments. For internal use only.
    """

    reference = args.get("reference")
    logfolder = args.get("logfolder")
    basefolder = args.get("basefolder")
    if not basefolder:
        basefolder = args.get("studyfolder")
    sessionsfolder = args.get("sessionsfolder")
    sourcefolder = args.get("sourcefolder")
    folder = args.get("folder")

    if sessionsfolder:
        sessionsfolder = os.path.abspath(sessionsfolder)

    if basefolder is None:
        if sessionsfolder:
            basefolder = os.path.dirname(sessionsfolder)
        else:
            for f in [
                os.path.abspath(e)
                for e in [logfolder, sourcefolder, folder, reference, "."]
                if e
            ]:
                if f and not basefolder:
                    while os.path.dirname(f) and os.path.dirname(f) != "/":
                        f = os.path.dirname(f)
                        if os.path.exists(os.path.join(f, ".qunexstudy")):
                            basefolder = f
                            break
                        elif os.path.exists(os.path.join(f, ".mnapstudy")):
                            basefolder = f
                            break

    if logfolder is None and timestamp and command:
        if basefolder:
            logfolder = os.path.join(basefolder, "logs", f"{timestamp}_{command}")
        else:
            logfolder = os.path.join(os.path.abspath("."), f"{timestamp}_{command}")
    elif logfolder == "legacy" or (not timestamp and not command):
        if basefolder:
            logfolder = os.path.join(basefolder, "processing", "logs")
        else:
            logfolder = os.path.abspath(".")

    if logfolder is None:
        homedir = os.path.expanduser("~")
        logfolder = os.path.join(homedir, "qunex")

    return {
        "basefolder": basefolder,
        "sessionsfolder": sessionsfolder,
        "logfolder": logfolder,
    }


def run_external_parallel(calls, cores=None, prepend=""):
    """
    ``run_external_parallel(calls, cores=None, prepend='')``

    Runs external commands specified in 'calls' in parallel utilizing all the
    available or the number of cores specified in 'cores'.

    Parameters:
        --calls (list):
            A list of dictionaries that specifies the commands to run. It should
            consists of:

            - 'name' ... the name of the command to run
            - 'args' ... the actual command provided as a list of arguments
            - 'sout' ... the name of the log file to which to direct the
              standard output from the command ran.

        --cores (int | str, default 'all'):
            Number of elements to run in parallel for grayordinate
            decomposition. If specified as None or 'all', all available elements
            (3 max for left surface, right surface and volume files) will be
            used. One element per CPU core is processed at a time.

        --prepend (str):
            The string to prepend to each line of progress report.

    Examples:
        ::

            run_external_parallel({'name': 'List all zip files', 'args': ['ls' '-l' '*.zip'], 'sout': 'zips.log'}, \\
            cores=1, prepend=' ... ')
    """

    if cores is None or cores in ["all", "All", "ALL"]:
        try:
            cores = len(os.sched_getaffinity(0))
        except Exception:
            cores = multiprocessing.cpu_count()
    else:
        try:
            cores = int(cores)
        except Exception:
            cores = 1

    running = []
    completed = []

    while True:
        # --- check if we can add a process to run
        if len(running) < cores:
            if calls:
                call = calls.pop(0)
                if call["sout"]:
                    if os.path.exists(call["sout"]):
                        sout = open(call["sout"], "a", 1)
                    else:
                        sout = open(call["sout"], "w", 1)
                else:
                    sout = open(os.devnull, "w")

                print(
                    "Starting log for %s at %s\nThe command being run: \n>> %s\n"
                    % (
                        call["name"],
                        str(datetime.now()).split(".")[0],
                        " ".join(call["args"]),
                    ),
                    file=sout,
                )

                try:
                    if "shell" in call and call["shell"]:
                        running.append(
                            {
                                "call": call,
                                "sout": sout,
                                "p": subprocess.Popen(
                                    call["args"],
                                    stdout=sout,
                                    stderr=sout,
                                    bufsize=0,
                                    shell=True,
                                ),
                            }
                        )
                    else:
                        running.append(
                            {
                                "call": call,
                                "sout": sout,
                                "p": subprocess.Popen(
                                    call["args"], stdout=sout, stderr=sout, bufsize=0
                                ),
                            }
                        )

                    if call["sout"]:
                        print(
                            prepend
                            + "started running %s at %s, track progress in %s"
                            % (
                                call["name"],
                                str(datetime.now()).split(".")[0],
                                call["sout"],
                            )
                        )
                    else:
                        print(
                            prepend
                            + "started running %s at %s"
                            % (call["name"], str(datetime.now()).split(".")[0])
                        )
                except Exception:
                    print(
                        prepend
                        + "ERROR: failed to start running %s. Please check your environment!"
                        % (call["name"])
                    )
                    completed.append(
                        {
                            "exit": -9,
                            "name": call["name"],
                            "log": call["sout"],
                            "args": call["args"],
                        }
                    )
                continue

        # --- check if a process finished
        done = []
        for n in range(len(running)):
            running[n]["sout"].flush()

            if running[n]["p"].poll() is not None:
                running[n]["sout"].close()
                if running[n]["call"]["sout"]:
                    print(
                        prepend
                        + "finished running %s (exit code: %d), log in %s"
                        % (
                            running[n]["call"]["name"],
                            running[n]["p"].poll(),
                            running[n]["call"]["sout"],
                        )
                    )
                else:
                    print(
                        prepend
                        + "finished running %s (exit code: %d)"
                        % (running[n]["call"]["name"], running[n]["p"].poll())
                    )
                completed.append(
                    {
                        "exit": running[n]["p"].poll(),
                        "name": running[n]["call"]["name"],
                        "log": running[n]["call"]["sout"],
                        "args": running[n]["call"]["args"],
                    }
                )
                done.append(n)
        if done:
            while done:
                running.pop(done.pop())
            continue

        # --- check if we are done:
        if not calls and not running:
            print(prepend + "DONE")
            break

        # --- wait a bit
        time.sleep(1)

    return completed


results = []
lock = multiprocessing.Lock()


def record(response):
    """
    ``record(response)``

    Appends response from a completed function.

    For internal use only.
    """

    global results

    results.append(response)

    with lock:
        name, result, target_log, prepend = response
        if target_log:
            see = " [log: %s]." % (target_log)
        else:
            see = "."

        if result:
            print("%s%s failed%s" % (prepend, name, see))
        else:
            print("%s%s finished successfully%s" % (prepend, name, see))


def record_future(future):
    if future.exception() is not None:
        print("Unhandled exception")
        print(future.exception())
    else:
        record(future.result())


# Logger class that prints both to stdour and to console
class Logger(object):
    def __init__(self, logfile):
        self.terminal = sys.stdout
        self.log = open(logfile, "a")

    def write(self, message):
        self.terminal.write(message)
        self.log.write(message)

    def close(self):
        self.log.close()

    def flush(self):
        # this flush method is needed for python 3 compatibility.
        # this handles the flush command by doing nothing.
        # you might want to specify some extra behavior here.
        pass


def run_with_log(function, args=None, logfile=None, name=None, prepend=""):
    """
    ``run_with_log(function, args=None, logfile=None, name=None)``

    Runs a function with the arguments by redirecting standard output and
    standard error to the specified log file.

    For internal use only.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d_%H.%M.%S.%f")

    if name is None:
        name = function.__name__

    if logfile:
        logfolder, logname = os.path.split(logfile)

        base_logname, ext_logname = os.path.splitext(logname)
        logname = base_logname + "_" + timestamp + ext_logname

        # truncate too long lognames
        max_log_length = 150
        if len(logname) > max_log_length:
            logname = logname[:max_log_length] + "(...).log"

        tlogfile = os.path.join(logfolder, "tmp_" + logname)

        if not os.path.exists(logfolder):
            os.makedirs(logfolder)
        with lock:
            # header
            with open(tlogfile, "w") as f:
                print_qunex_header(timestamp=timestamp, file=f)
                print("#", file=f)
            print(
                prepend
                + "started running %s at %s, track progress in %s"
                % (name, str(datetime.now()).split(".")[0], tlogfile)
            )

        sysstdout = sys.stdout
        sysstderr = sys.stderr
        sys.stdout = Logger(tlogfile)
        sys.stderr = sys.stdout
    else:
        with lock:
            print(print_qunex_header(timestamp=timestamp))
            print("#")
            print(
                prepend
                + "started running %s at %s" % (name, str(datetime.now()).split(".")[0])
            )

    with lock:
        print(
            "call: gmri %s %s\n-----------------------------------------"
            % (
                function.__name__,
                " ".join(['%s="%s"' % (k, v) for (k, v) in args.items()]),
            )
        )

    try:
        # remove logfolder from args if it is not in function's footprint
        if (
            "logfolder" in args
            and "logfolder" not in inspect.signature(function).parameters
        ):
            del args["logfolder"]
        result = function(**args)
    except ge.CommandError as e:
        with lock:
            print(ge.report_command_error(name, e))
        result = e
    except ge.CommandNull as e:
        with lock:
            print(ge.report_command_null(name, e))
        result = e
    except ge.CommandFailed as e:
        with lock:
            print(ge.report_command_failed(name, e))
        result = e
    except Exception as e:
        with lock:
            print("\n\nERROR")
            print(traceback.format_exc())
        result = e

    with lock:
        print(
            "\n-----------------------------------------\nFinished at %s"
            % (datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
        )

    # schedule command fix
    if name == "schedule":
        result = False

    if not result:
        print(f"\n---> Successful completion of task at {datetime.now()}")

    if logfile:
        sys.stdout.close()
        sys.stdout = sysstdout
        sys.stderr = sysstderr

        # log prefix
        log_prefix = "done_"
        if result:
            log_prefix = "error_"
        comlogname = os.path.join(logfolder, log_prefix + logname)

        os.rename(os.path.join(logfolder, "tmp_" + logname), comlogname)

        # create runlog, which sits in the parent of the comlogs folder
        parent, tail = os.path.split(logfolder.rstrip(os.sep))
        if tail == "comlogs":
            logfolder = parent

        # runlog file
        runlogname = "Log-" + logname

        # print to runlog file and close
        logfile = os.path.join(logfolder, runlogname)
        lf = open(logfile, "a")

        # header
        lf.write("%s\n" % (print_qunex_header(timestamp=timestamp)))
        lf.write("#\n")

        # split name to command name and session
        split = name.split(": ")

        # print session if exists
        if len(split) > 1:
            lf.write("session: %s\n" % split[1])

        # print command name
        lf.write("qunex %s \\\n" % split[0])
        arg_items = list(args.items())
        for i, (k, v) in enumerate(arg_items):
            if i < len(arg_items) - 1:
                lf.write('  --%s="%s" \\\n' % (k, v))
            else:
                lf.write('  --%s="%s"\n' % (k, v))

        # print final status
        if result:
            lf.write("\nERROR running %s\n" % name)
        else:
            lf.write(f"\n---> Successful completion of task at {datetime.now()}\n")

        lf.close()
    else:
        comlogname = None

    return name, result, comlogname, prepend


def run_in_parallel(calls, cores=None, prepend=""):
    """
    ``run_in_parallel(calls, cores=None, prepend="")``

    Runs functions specified in 'calls' in parallel utilizing all the available
    or the number of cores specified in 'cores'.

    INPUTS
    ======

    --calls        A list of dictionaries that specifies the commands to run.
                   It should consists of:

                   - name (the name of the command to run)
                   - function (the function to be run)
                   - args (the arguments to be passed to the function)
                   - logfile (the path to the log file to which to direct the
                     standard output from the command ran)

    --cores        The number of cores to utilize. If specified as None or
                   'all', all available cores will be utilized.
    --prepend      The string to prepend to each line of progress report.

    EXAMPLE USE
    ===========

    ::

        run_in_parallel({'name': 'Sort dicom files', 'function': dicom.sort_dicom, 'args': {'folder': '.'}, 'sout': 'sort_dicom.log'}, cores=1, prepend=' ... ')
    """

    global results

    if cores is None or cores in ["all", "All", "ALL"]:
        cores = len(os.sched_getaffinity(0))
    else:
        try:
            cores = int(cores)
        except Exception:
            cores = 1

    results = []
    with ProcessPoolExecutor(max_workers=cores) as executor:
        for call in calls:
            future = executor.submit(
                run_with_log,
                call["function"],
                call["args"],
                call["logfile"],
                call["name"],
                prepend,
            )
            future.add_done_callback(record_future)

    return results


def check_files(test_folder, spec_file, fields=None, report=None, append=False):
    """
    ``check_files(test_folder, spec_file, fields=None, report=None, append=False)``

    Check the test_folder for presence of files as specified in spec_file, which
    lists files one per line with space delimited paths. Additionally an array
    of key-value pairs can be provided. If present every instance of {<key>}
    will be replaced by <value>. If report is specified, a report will be
    written to that file. Where there might be two alternative options of results
    e.g. difference because of AP/PA direction, then the alternative is to
    be provided in the same line separated by a pipe '|'
    """

    # --- open the report if needed:

    if report:
        if type(report) is types.FileType:
            rout = report
            file_close = False
        else:
            file_close = True
            try:
                if append:
                    rout = open(report, "a")
                else:
                    rout = open(report, "w")
            except Exception:
                raise ge.CommandFailed(
                    "check_files",
                    "Report file could not be opened",
                    "Failed to open a report file for writing: %s" % (report),
                    "Please check your settings and paths!",
                )
        print(
            "\n#-----------------------------------------\n# Full file check report\n# . denotes file present\n# X denotes file absent\n",
            file=rout,
        )

    # --- initial tests

    if not os.path.exists(test_folder):
        print(
            "The folder to be tested does not exist: %s \nPlease check your settings and paths!"
            % (test_folder),
            file=rout,
        )
        print(
            "\n#-----------------=== End Full File Report ===----------------------",
            file=rout,
        )
        if file_close:
            rout.close()
        raise ge.CommandFailed(
            "check_files",
            "Folder to test does not exist",
            "The folder to be tested does not exist: %s" % (test_folder),
            "Please check your settings and paths!",
        )

    if not os.path.exists(spec_file):
        print(
            "The specification file to test folder against does not exist: %s\nPlease check your settings and paths!"
            % (spec_file),
            file=rout,
        )
        print(
            "\n#-----------------=== End Full File Report ===----------------------",
            file=rout,
        )
        if file_close:
            rout.close()
        raise ge.CommandFailed(
            "check_files",
            "Specification file does not exist",
            "The specification file to test folder against does not exist: %s"
            % (spec_file),
            "Please check your settings and paths!",
        )

    # --- read the spec

    files = open(spec_file, "r").read()

    if fields:
        for key, value in fields:
            files = files.replace("{%s}" % (key), value)

    files = [
        [f.strip().split() for f in e.split("|")]
        for e in files.split("\n")
        if len(e) and not e.startswith("#")
    ]

    # --- test the files

    present = []
    missing = []
    for testfiles in files:
        file_missing = True
        for testfile in testfiles:
            test = [test_folder] + testfile
            tfile = os.path.join(*test)
            if os.path.exists(tfile):
                present.append(tfile)
                file_missing = False
                if report:
                    print(". " + tfile, file=rout)
                break
        if file_missing:
            missing.append(tfile)
            if report:
                print("X " + tfile, file=rout)

    if report:
        print(
            "\n#-----------------=== End Full File Report ===----------------------",
            file=rout,
        )
        if file_close:
            rout.close()

    status = len(missing) == 0

    return status, present, missing


def print_and_log(*args, **kwargs):
    """
    ``print_and_log(*args, **kwargs)``

    Prints all that is given as nonpositional argument to the standard output.

    INPUTS
    ======

    --file         Prints to the file.
    --write        Creates a file and writes to it.
    --append       Opens a file and appends to it.
    --silent       Whether to not print to stdout.
    --end          How to end ['\n'].
    """

    silent = kwargs.get("silent", False)
    file = kwargs.get("file", None)
    write = kwargs.get("write", None)
    append = kwargs.get("append", None)
    end = kwargs.get("end", "\n")

    if write:
        write = open(write, "w")
    if append:
        append = open(append, "a")

    for element in args + (end,):
        if not silent:
            print(element, end=" ")
        for out in [append, write, file]:
            if out:
                print(element, end=" ", file=out)

    for toclose in [append, write]:
        if toclose:
            toclose.close()


def get_log_file(folders=None, tags=None):
    """
    ``get_log_file(folders=None, tags=None)``

    Creates a log file in the comlogs folder.

    INPUTS
    ======

    --folders      A dictionary with the known paths.
    --tags         An array of strings to use to create the filename.

    OUTPUTS
    =======

    --filename         The path to the log file.
    --file handle      The file handle of the open file.

    USE
    ===

    Creates a log file in the comlogs folder and returns the name and the file
    handle. It tries to find the correct location for the log based on the
    provided folders.

    """

    folders = deduce_folders(folders)

    if "logfolder" not in folders:
        raise ge.CommandFailed(
            "get_log_file",
            "Logfolder not found",
            "Could not deduce the location of the log folder based on the provided information!",
        )

    basestring = (str, bytes)
    if isinstance(tags, basestring) or tags is None:
        tags = []

    logstamp = datetime.now().strftime("%Y-%m-%d_%H.%M.%S.%f")
    logname = tags + [logstamp]
    logname = [e for e in logname if e]
    logname = "_".join(logname)
    logname = os.path.join(folders["logfolder"], "comlogs", "tmp_%s.log" % (logname))
    logfile = open(logname, "w")

    return logname, logfile


def close_log_file(logfile=None, logname=None, status="done"):
    """
    ``close_log_file(logfile=None, logname=None, status="done")``

    Closes the logfile and swaps the 'tmp_', 'done_', 'error_', 'incomplete_' at
    the start of the logname to the provided status.

    Returns the path of the renamed log file, or None if no logname was given.
    """

    newfile = None

    if logfile:
        logfile.close()

    if logname:
        logfolder, newname = os.path.split(logname)
        newname = re.sub("^(tmp_|done_|error_|incomplete_|)", status + "_", newname)
        newfile = os.path.join(logfolder, newname)
        os.rename(logname, newfile)

    return newfile


def underscore(s):
    s = s + "\n" + "".join(["=" for e in range(len(s))])
    return s


def plist(s):
    """
    plist(s)
    Processes the string, spliting it by the pipe "|" symbol, trimming
    any whitespace caracters from start or end of each resulting
    substring, and retuns an array of substrings of length more than 0.
    """
    s = s.split("|")
    s = [e.strip() for e in s]
    s = [e for e in s if len(e) > 0]
    return s


def pcslist(s):
    """
    pcslist(s)
    Processes the string, spliting it by the pipe "|", comma or space, trimming
    any whitespace caracters from start or end of each resulting substring, and
    retuns an array of substrings of length more than 0.
    """
    s = re.split(r" *, *| *\| *| +", s)
    s = [e.strip() for e in s]
    s = [e for e in s if len(e) > 0]
    return s


def link_or_copy(
    source, target, r=None, status=None, name=None, prefix=None, symlink=False
):
    """
    Hard-link a file, falling back to a copy, and report the outcome.

    Parameters:
        source (str): path to the file to map.
        target (str): destination path.
        r (str | None): report so far; when given, the mapping outcome is
            appended and returned alongside the status.
        status (bool | None): running status carried through (defaults True).
        name (str | None): human readable name used in the report message.
        prefix (str | None): prefix for the report message (defaults ``"\n ... "``).
        symlink (bool): create a symbolic link instead of a hard link.

    Returns:
        bool | tuple: the status when ``r`` is None, otherwise
        ``(status, report_with_outcome_appended)``.
    """
    if status is None:
        status = True
    if name is None:
        name = "file"
    if prefix is None:
        prefix = "\n ... "
    if os.path.exists(source):
        try:
            if os.path.exists(target):
                if os.path.samefile(source, target):
                    if r is None:
                        return status and True
                    else:
                        return (
                            status and True,
                            "%s%s%s already mapped" % (r, prefix, name),
                        )
                else:
                    os.remove(target)

            # link
            if not symlink:
                os.link(source, target)
            else:
                os.symlink(source, target)

            if r is None:
                return status and True
            else:
                return (status and True, "%s%s%s mapped" % (r, prefix, name))

        except Exception:
            try:
                shutil.copy2(source, target)
                if r is None:
                    return status and True
                else:
                    return (status and True, "%s%s%s copied" % (r, prefix, name))
            except Exception:
                if r is None:
                    return False
                else:
                    return (
                        False,
                        "%s%sERROR: %s could not be copied, check permissions! "
                        % (r, prefix, name),
                    )
        return True
    else:
        if r is None:
            return False
        else:
            return (
                False,
                "%s%sERROR: %s could not be copied, source file does not exist [%s]! "
                % (r, prefix, name, source),
            )


def move_link_or_copy(
    source, target, action=None, r=None, status=None, name=None, prefix=None, lock=False
):
    """
    Map a file into place by moving, hard-linking or copying it.

    Parameters:
        source (str): path to the file to map.
        target (str): destination path.
        action (str | None): one of ``"move"``, ``"link"`` or ``"copy"``
            (defaults ``"link"``).
        r (str | None): report so far; when given, the outcome is appended and
            returned alongside the status.
        status (bool | None): running status carried through (defaults True).
        name (str | None): human readable name used in the report message
            (defaults to ``source``).
        prefix (str | None): prefix for the report message.
        lock (bool): serialise the mapping with a file lock to make it safe for
            concurrent callers.

    Returns:
        bool | tuple: the status when ``r`` is None, otherwise
        ``(status, report_with_outcome_appended)``.
    """
    if action is None:
        action = "link"
    if status is None:
        status = True
    if name is None:
        name = source
    if prefix is None:
        prefix = ""

    def report(rstatus, msg):
        if lock:
            fl.unlock(target)
        if r is None:
            return rstatus
        else:
            return rstatus, r + prefix + msg

    if os.path.exists(source):
        targetfolder = os.path.dirname(target)
        if not os.path.exists(targetfolder):
            io = fl.makedirs(targetfolder)
            if io:
                if io != "File exists":
                    return report(
                        False,
                        "ERROR: %s could not be %sed, target folder could not be created, check permissions! "
                        % (name, action),
                    )

        if lock:
            fl.lock(target)

        if action == "link":
            io = fl.link(source, target)
            if not io:
                return report(status, "%s mapped" % (name))
            elif io == "File exists":
                if os.path.samefile(source, target):
                    return report(status, "%s already mapped [%s]" % (name, target))
                else:
                    io = fl.remove(target)
                    if io and io != "No such file or directory":
                        return report(
                            False,
                            "ERROR: %s could not be %sed, existing file could not be removed, check permissions! "
                            % (name, action),
                        )
                    io = fl.link(source, target)
                    if not io:
                        return report(status, "%s mapped" % (name))
                    else:
                        action = "copy"
            else:
                action = "copy"

        if action == "copy":
            try:
                shutil.copy2(source, target)
                return report(status, "%s copied" % (name))
            except Exception:
                return report(
                    False, "ERROR: %s could not be copied, check permissions! " % (name)
                )

        if action == "move":
            try:
                shutil.move(source, target)
                return report(status, "%s moved" % (name))
            except Exception:
                return report(
                    False, "ERROR: %s could not be moved, check permissions! " % (name)
                )

        if action == "gzip":
            try:
                with open(source, "rb") as f_in, gzip.open(target, "wb") as f_out:
                    shutil.copyfileobj(f_in, f_out)
                return report(status, "%s copied and gzipped" % (name))
            except Exception:
                return report(
                    False,
                    "ERROR: %s could not be copied and gzipped, check permissions! "
                    % (name),
                )

    else:
        return report(
            False,
            "WARNING: %s could not be %sed, source file either does not exist or can not be accessed [%s]! "
            % (name, action, source),
        )


def create_session_file(command, sfolder, session, subject, overwrite, prefix=""):
    """
    ``create_session_file(command, sfolder, session, subject, overwrite, prefix)``

    Creates the generic, non pipeline specific, session file.
    """

    # open fifle
    sfile = os.path.join(sfolder, "session.txt")
    if os.path.exists(sfile):
        if overwrite == "yes" or overwrite is True:
            os.remove(sfile)
            print(prefix + "---> removed existing session.txt file")
        else:
            raise ge.CommandFailed(
                command,
                "session.txt file already present!",
                "A session.txt file alredy exists [%s]" % (sfile),
                "Please check or set parameter 'overwrite' to 'yes' to rebuild it!",
            )

    sout = open(sfile, "w")
    print_qunex_header(file=sout)
    print("#", file=sout)
    print("session:", session, file=sout)
    print("subject:", subject, file=sout)

    # bids
    bfolder = os.path.join(sfolder, "bids")
    if os.path.exists(bfolder):
        print("bids:", bfolder, file=sout)

    # nii
    nfolder = os.path.join(sfolder, "nii")
    if os.path.exists(bfolder):
        print("raw_data:", nfolder, file=sout)

    # hcp
    hfolder = os.path.join(sfolder, "hcp")
    print("hcp:", hfolder, file=sout)

    # empty line
    print(file=sout)

    # return
    return sout


def get_qunex_version():
    """
    Returns the version of currently used QuNex suite.
    """

    # open the version file and read its contents
    with open(
        os.path.join(os.environ["TOOLS"], os.environ["QUNEXREPO"], "VERSION.md"), "r"
    ) as f:
        version = f.read().strip()

    return version
