#!/usr/bin/env python
# encoding: utf-8

# SPDX-FileCopyrightText: 2021 QuNex development team <https://qunex.yale.edu/>
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""
``core.py``

This file holds code for core support functions used by other code for
preprocessing and analysis. The functions are for internal use
and can not be called externally.
"""

import contextlib
import glob
import gzip
import inspect
import re
import fnmatch
import os.path
import multiprocessing
import os
import os.path
import shutil
import subprocess
import time
import traceback
from concurrent.futures import ProcessPoolExecutor
from datetime import datetime

from collections import UserList, namedtuple
from copy import deepcopy

import qx_utilities.general.filelock as fl
import qx_utilities.general.exceptions as ge


def print_qunex_header(timestamp=None, file=None):
    """
    ``print_qunex_header(timestamp=None, file=None)``

    Prepares and returns a standard "Generated by QuNex" string. If file
    is not None, it prints it to the specified file. If timestamp is not
    none, it uses the specified timestamp, which can be either a string
    or a datetime object.
    """
    if timestamp is None:
        timestamp = datetime.now().strftime("%Y-%m-%d_%H.%M.%S.%f")
    elif type(timestamp) is datetime:
        timestamp = timestamp.strftime("%Y-%m-%d_%H.%M.%S.%f")

    header = f"# Generated by QuNex {get_qunex_version()} on {timestamp}"
    if file:
        print(header, file=file)

    return header


# ==============================================================================
#                                              SESSION AND SUBJECT LIST HANDLING

# ------------------------------------------------------------------------------
#                                                              SessionList class

class SessionList(UserList):
    """
    ``SessionList``

    A list subclass for session and subject data.
    """
    def __init__(self, initialdata=None):
        if initialdata is None:
            initialdata = []
        super().__init__(initialdata)

    def copy(self):
        """
        ``copy()``

        Returns a deep copy of the SessionList.
        """
        return SessionList(deepcopy(self.data))

    def filter_by_key(self, key, value):
        """
        ``filter_by_key(key, value)``

        Filter the SessionList by key and value.
        - If value is a list, matches any of the values.
        - Values may be glob patterns (*, ?, [a-z]).
        """
        def matches(item_value, pattern):
            # Exact match for non-strings
            if not isinstance(item_value, str):
                return item_value == pattern

            # Glob match for strings
            return item_value == pattern or fnmatch.fnmatchcase(item_value, pattern)

        # Normalize value to list
        if isinstance(value, str):
            if "," in value:
                values = [e.strip() for e in value.split(",")]
            else:
                values = [value]
        # values = value if isinstance(value, list) else [value]

        return SessionList([
            deepcopy(e)
            for e in self.data
            if isinstance(e, dict)
            and key in e
            and any(matches(e[key], v) for v in values)
        ])

    def filter_by_string(self, filter):
        """
        Filter the SessionList by a filter string.

        - Use '|' between <key>:<value> pairs for OR
        Example: "group:pat*|task:rest"

        - Use '&' between <key>:<value> pairs for AND
        Example: "group:pat*&task:r?st"

        Values are treated as globs (fnmatch):
        * matches any chars, ? matches one char, [abc] matches one char in set.

        Only one operator type may be used.
        """
        if filter is None or filter.strip() == "":
            return SessionList([])  # or return a copy of self, if you prefer

        fstr = filter.strip()

        has_or = "|" in fstr
        has_and = "&" in fstr
        if has_or and has_and:
            raise ge.CommandFailed(
                "SessionList.filter_by_string",
                "Invalid filter parameter",
                "The provided filter parameter is invalid: '%s'" % (filter),
                "Use either '|' (OR) or '&' (AND), but not both.",
                "Please adjust the parameter!",
            )

        op = "|" if has_or else ("&" if has_and else None)
        parts = [fstr] if op is None else fstr.split(op)

        try:
            filters = [[p.strip() for p in e.split(":", 1)] for e in parts]
        except Exception:
            filters = []

        if any(len(e) != 2 or e[0] == "" or e[1] == "" for e in filters):
            raise ge.CommandFailed(
                "SessionList.filter_by_string",
                "Invalid filter parameter",
                "The provided filter parameter is invalid: '%s'" % (filter),
                "The parameter should be a '%s' separated string of <key>:<value> pairs!"
                % (op if op else "(single)"),
                "Please adjust the parameter!",
            )

        def matches(item, key, pattern):
            if not (isinstance(item, dict) and key in item):
                return False

            v = item[key]

            # Exact match for non-strings
            if not isinstance(v, str):
                return v == pattern

            # For strings: exact OR glob match
            # (fnmatchcase is case-sensitive and does not depend on OS)
            return v == pattern or fnmatch.fnmatchcase(v, pattern)

        filtered_data = []
        for s in self.data:
            if op == "&":
                ok = all(matches(s, key, pattern) for key, pattern in filters)
            else:
                ok = any(matches(s, key, pattern) for key, pattern in filters)

            if ok:
                filtered_data.append(deepcopy(s))

        return SessionList(filtered_data)

    def get_list_by_key(self, key, sep=","):
        """
        ``get_list_by_key(key, sep=",")``

        Compile a list of unique values for the specified key. By default it returns
        a comma separated string. If sep is None or empty string, it returns a list.
        """
        if sep is None or sep == "":
            return list(dict.fromkeys(str(item[key]) for item in self.data if key in item))
        else:
            return sep.join(list(dict.fromkeys(str(item[key]) for item in self.data if key in item)))

    def group_by_key(self, key):
        """
        ``group_by_key(key)``

        Groups the SessionList by the specified key. Returns a list of SessionLists.
        """
        groups = {}

        for item in self.data:
            if isinstance(item, dict) and key in item:
                group_value = item[key]
                groups.setdefault(group_value, []).append(deepcopy(item))

        return [SessionList(items) for items in groups.values()]

    def dont_have_key(self, key):
        """
        ``dont_have_key(key)``

        Reports the items that do not have the specified key or have it as None or empty.
        Returns list of such items.
        """
        return SessionList([item for item in self.data if not (isinstance(item, dict) and key in item and item[key] is not None and item[key].strip() != "")])

    def have_key(self, key):
        """
        ``have_key(key)``

        Returns all the items that have the specified key with a value that is not None or empty.
        Returns list of such items.
        """
        return SessionList([item for item in self.data if (isinstance(item, dict) and key in item and item[key] is not None and item[key].strip() != "")])


# ------------------------------------------------------------------------------
#                           Read session data from batch.txt or session.txt file


def read_session_data(filename, verbose=False):
    """
    ``read_session_data(filename, verbose=False)``

    Reads a `batch.txt` file.

    USE
    ===

    An internal function for reading `batch.txt` and `session.txt` files. It
    reads the file and returns a list of sessions with the information on images
    and the additional parameters specified in the header.

    """

    if not os.path.exists(filename):
        print(
            "\n\n=====================================================\nERROR: Source file does not exist [%s]"
            % (filename)
        )
        raise ValueError("ERROR: Batch file not found: %s" % (filename))

    with open(filename, "r") as file:
        s = file.read()

    s = s.replace("\r", "\n")
    s = s.replace("\n\n", "\n")
    s = re.sub("^#.*?\n", "", s)

    s = s.split("\n---")
    s = [e for e in s if len(e) > 10]

    nsearch = re.compile(r"(.*?)\((.*)\)")
    csearch = re.compile(r"c([0-9]+)$")

    slist = []
    gpref = {}

    c = 0
    # first "session" is the parameters block
    first = True
    try:
        for sub in s:
            sub = sub.split("\n")
            sub = [e.strip() for e in sub]
            sub = [e.split("#")[0].strip() for e in sub]
            sub = [e for e in sub if len(e) > 0]

            dic = {}
            for line in sub:
                c += 1

                # --- read preferences / settings
                if line.startswith("--"):
                    pkey, pvalue = [e.strip() for e in line.split(":", 1)]
                    if first:
                        gpref[pkey[2:]] = pvalue
                    else:
                        dic[pkey] = pvalue
                    continue

                elif line.startswith("_") or line.startswith("-"):
                    pkey, pvalue = [e.strip() for e in line.split(":", 1)]
                    if first:
                        gpref[pkey[1:]] = pvalue
                    else:
                        dic[pkey] = pvalue
                    continue

                # --- split line
                line = line.split(":")
                line = [e.strip() for e in line]
                if len(line) < 2:
                    continue

                # --- read ima data
                if line[0].isdigit():
                    image = {}
                    image["ima"] = line[0]
                    remove = []
                    for e in line:
                        m = nsearch.match(e)
                        if m:
                            image[m.group(1).strip()] = m.group(2).strip()
                            remove.append(e)

                    for e in remove:
                        line.remove(e)

                    ni = len(line)
                    if ni > 1:
                        image["name"] = line[1]
                    if ni > 2 and ("bold" in image["name"]) or ("DWI" in image["name"]):
                        image["task"] = line[2]
                    if ni > 3:
                        image["ext"] = line[3]

                    dic[line[0]] = image

                # --- read conc data
                elif csearch.match(line[0]):
                    conc = {}
                    conc["cnum"] = line[0]
                    for e in line:
                        m = nsearch.match(e)
                        if m:
                            conc[m.group(1).strip()] = m.group(2).strip()
                            line.remove(e)

                    ni = len(line)
                    if ni < 3:
                        print("Missing data for conc entry!")
                        raise AssertionError(
                            "Not enough values in conc definition line!"
                        )

                    conc["label"] = line[1]
                    conc["conc"] = line[2]
                    conc["fidl"] = line[3]
                    dic[line[0]] = conc

                # --- read rest of the data
                else:
                    dic[line[0]] = ":".join(line[1:])

            if len(dic) > 0:
                if ("id" not in dic) and ("session" not in dic):
                    if verbose:
                        print(
                            "WARNING: There is a record missing an id field and is being omitted from processing."
                        )
                else:
                    if "id" in dic and "session" not in dic:
                        dic["session"] = dic["id"]
                    elif "session" in dic and "id" not in dic:
                        dic["id"] = dic["session"]
                    slist.append(dic)

            # check paths
            for field in ["dicom", "raw_data", "data", "hpc"]:
                if field in dic:
                    if not os.path.exists(dic[field]) and verbose:
                        print(
                            "WARNING: session %s - folder %s: %s specified in %s does not exist! Check your paths!"
                            % (dic["id"], field, dic[field], os.path.basename(filename))
                        )

            # done with the parameters block
            first = False

    except Exception:
        print(
            "\n\n=====================================================\nERROR: There was an error with the batch.txt file in line %d:\n---> %s\n\n--------\nError raised:\n"
            % (c, line)
        )
        raise

    return slist, gpref

# ------------------------------------------------------------------------------
#                                              Read session data from .list file


def read_list(filename, verbose=False):
    """
    ``read_list(filename, verbose=False)``

    An internal function for reading list files. It reads the file and
    returns a list of sessions each with the provided list of files.
    """

    slist = []
    session = {}

    with open(filename) as f:
        for line in f:
            if line.strip()[:1] == "#":
                continue

            line = [e.strip() for e in line.split(":")]

            if len(line) == 2:
                if line[0] == "session id":
                    if session != {}:
                        slist.append(session.copy())
                    session = {}
                    session["id"] = line[1]

                else:
                    if line[0] in session:
                        session[line[0]].append(line[1])
                    else:
                        session[line[0]] = [line[1]]
        slist.append(session)
    return slist

# ------------------------------------------------------------------------------
#                                       Compile session list from various inputs


def get_sessions_list(
    list_string, filter=None, sessionids=None, sessionsfolder=None, verbose=False
):
    """
    ``get_sessions_list(list_string, filter=None, sessionids=None, sessionsfolder=None, verbose=False)``

    Gets a list of sessions as an array of dictionaries.

    USE
    ===

    An internal function for getting a list of sessions as an array of
    dictionaries in the form::

        [{'id': <session id>, [... other keys]}, {'id': <session id>, [... other keys]}]

    The provided list_string can be:

    - a comma, space or pipe separated list of session id codes,
    - a path to a batch file (identified by .txt extension),
    - a path to a `*.list` file (identified by .list extension).

    In the first cases, the dictionary will include only session ids, in the
    second all the other information present in the batch file, in the third
    lists of specified files, e.g.::

        [{'id': <session id>, 'file': [<first file>, <second file>], 'roi': [<first file>], ...}, ...]

    If filter is provided (not None), only sessions that match the filter will
    be returned. If sessionids is provided (not None), only sessions with
    matching id will be returned. If sessionsfolder is provided (not None),
    sessions from a list_string will be treated as glob patterns and all folders
    that match the pattern in the sessionsfolder will be returned as session
    ids.
    """

    gpref = {}

    list_string = list_string.strip()

    if re.match(r".*\.list$", list_string):
        slist = read_list(list_string, verbose=verbose)

    elif os.path.isfile(list_string):
        slist, gpref = read_session_data(list_string, verbose=verbose)

    elif (
        re.match(r".*\.txt$", list_string) or "/" in list_string
    ) and not sessionids:
        raise ValueError(
            f"ERROR: The specified session file is not found and sessionids are not provided! [{list_string}]!"
        )

    else:
        if (
            re.match(r".*\.txt$", list_string) or "/" in list_string
        ) and sessionids:
            list_string = sessionids

        slist = [e.strip() for e in re.split(r" +|,|\|", list_string)]

        if sessionsfolder is None:
            slist = [{"id": e} for e in slist]

        else:
            nlist = []
            for s in slist:
                nlist += glob.glob(os.path.join(sessionsfolder, s))
            slist = [{"id": os.path.basename(e)} for e in nlist]

    slist = SessionList(slist)

    verbose=True

    # filter with sessionids
    slist = slist.filter_by_key("id", sessionids) if sessionids is not None and sessionids.strip() != "" else slist

    # filter with filter
    slist = slist.filter_by_string(filter) if filter is not None and filter.strip() != "" else slist

    # are we inside a SLURM job array?
    if "SLURM_ARRAY_TASK_ID" in os.environ:
        # get ID for this job
        slurm_array_ix = int(os.environ["SLURM_ARRAY_TASK_ID"])

        # get size of job array
        slurm_array_size = int(os.environ["SLURM_ARRAY_TASK_MAX"]) + 1

        # get the chunk
        slist = slist[slurm_array_ix::slurm_array_size]

    return slist, gpref


# ==============================================================================
#                                                          EXECUTION AND LOGGING

def deduce_folders(args, command=None, timestamp=None):
    """
    ``deduce_folders(args)``

    Tries to deduce the location of study specific folders based on the provided
    arguments. For internal use only.
    """

    reference = args.get("reference")
    logfolder = args.get("logfolder")
    basefolder = args.get("basefolder")
    if not basefolder:
        basefolder = args.get("studyfolder")
    sessionsfolder = args.get("sessionsfolder")
    sourcefolder = args.get("sourcefolder")
    folder = args.get("folder")

    if sessionsfolder:
        sessionsfolder = os.path.abspath(sessionsfolder)

    if basefolder is None:
        if sessionsfolder:
            basefolder = os.path.dirname(sessionsfolder)
        else:
            for f in [
                os.path.abspath(e)
                for e in [logfolder, sourcefolder, folder, reference, "."]
                if e
            ]:
                # the starting folder is tested first: a command run from the
                # study root is still being run inside a study
                if f and not basefolder:
                    while f and f != "/":
                        if any(
                            os.path.exists(os.path.join(f, marker))
                            for marker in [".qunexstudy", ".mnapstudy"]
                        ):
                            basefolder = f
                            break
                        f = os.path.dirname(f)

    if logfolder is None and timestamp and command:
        if basefolder:
            logfolder = os.path.join(basefolder, "logs", f"{timestamp}_{command}")
        else:
            logfolder = os.path.join(os.path.abspath("."), f"{timestamp}_{command}")
    elif logfolder == "legacy" or (not timestamp and not command):
        if basefolder:
            logfolder = os.path.join(basefolder, "processing", "logs")
        else:
            logfolder = os.path.abspath(".")

    if logfolder is None:
        homedir = os.path.expanduser("~")
        logfolder = os.path.join(homedir, "qunex")

    return {
        "basefolder": basefolder,
        "sessionsfolder": sessionsfolder,
        "logfolder": logfolder,
    }


def run_external_parallel(calls, cores=None, _log=None):
    """
    ``run_external_parallel(calls, cores=None)``

    Runs external commands specified in 'calls' in parallel utilizing all the
    available or the number of cores specified in 'cores'.

    Parameters:
        --calls (list):
            A list of dictionaries that specifies the commands to run. It should
            consists of:

            - 'name' ... the name of the command to run
            - 'args' ... the actual command provided as a list of arguments
            - 'sout' ... the name of the log file to which to direct the
              standard output from the command ran.

        --cores (int | str, default 'all'):
            Number of elements to run in parallel for grayordinate
            decomposition. If specified as None or 'all', all available elements
            (3 max for left surface, right surface and volume files) will be
            used. One element per CPU core is processed at a time.

        --_log:
            The log to report progress into. The underscore keeps the parameter
            off the command line; it replaces the `prepend` string the callers
            used to pass, the nesting now coming from the caller's log.

    Examples:
        ::

            run_external_parallel({'name': 'List all zip files', 'args': ['ls' '-l' '*.zip'], 'sout': 'zips.log'}, \\
            cores=1)
    """
    import qx_utilities.general.log as gl

    log = gl.log_or_console(_log)

    if cores is None or cores in ["all", "All", "ALL"]:
        try:
            cores = len(os.sched_getaffinity(0))
        except Exception:
            cores = multiprocessing.cpu_count()
    else:
        try:
            cores = int(cores)
        except Exception:
            cores = 1

    running = []
    completed = []

    while True:
        # --- check if we can add a process to run
        if len(running) < cores:
            if calls:
                call = calls.pop(0)
                if call["sout"]:
                    if os.path.exists(call["sout"]):
                        sout = open(call["sout"], "a", 1)
                    else:
                        sout = open(call["sout"], "w", 1)
                else:
                    sout = open(os.devnull, "w")

                print(
                    "Starting log for %s at %s\nThe command being run: \n>> %s\n"
                    % (
                        call["name"],
                        str(datetime.now()).split(".")[0],
                        " ".join(call["args"]),
                    ),
                    file=sout,
                )

                try:
                    if "shell" in call and call["shell"]:
                        running.append(
                            {
                                "call": call,
                                "sout": sout,
                                "p": subprocess.Popen(
                                    call["args"],
                                    stdout=sout,
                                    stderr=sout,
                                    bufsize=0,
                                    shell=True,
                                ),
                            }
                        )
                    else:
                        running.append(
                            {
                                "call": call,
                                "sout": sout,
                                "p": subprocess.Popen(
                                    call["args"], stdout=sout, stderr=sout, bufsize=0
                                ),
                            }
                        )

                    if call["sout"]:
                        log.detail(
                            "started running %s at %s, track progress in %s"
                            % (
                                call["name"],
                                str(datetime.now()).split(".")[0],
                                call["sout"],
                            )
                        )
                    else:
                        log.detail(
                            "started running %s at %s"
                            % (call["name"], str(datetime.now()).split(".")[0])
                        )
                except Exception:
                    log.error(
                        "failed to start running %s. Please check your environment!"
                        % (call["name"])
                    )
                    completed.append(
                        {
                            "exit": -9,
                            "name": call["name"],
                            "log": call["sout"],
                            "args": call["args"],
                        }
                    )
                continue

        # --- check if a process finished
        done = []
        for n in range(len(running)):
            running[n]["sout"].flush()

            if running[n]["p"].poll() is not None:
                running[n]["sout"].close()
                if running[n]["call"]["sout"]:
                    log.detail(
                        "finished running %s (exit code: %d), log in %s"
                        % (
                            running[n]["call"]["name"],
                            running[n]["p"].poll(),
                            running[n]["call"]["sout"],
                        )
                    )
                else:
                    log.detail(
                        "finished running %s (exit code: %d)"
                        % (running[n]["call"]["name"], running[n]["p"].poll())
                    )
                completed.append(
                    {
                        "exit": running[n]["p"].poll(),
                        "name": running[n]["call"]["name"],
                        "log": running[n]["call"]["sout"],
                        "args": running[n]["call"]["args"],
                    }
                )
                done.append(n)
        if done:
            while done:
                running.pop(done.pop())
            continue

        # --- check if we are done:
        if not calls and not running:
            log.detail("DONE")
            break

        # --- wait a bit
        time.sleep(1)

    return completed


results = []
lock = multiprocessing.Lock()

# What one call through `run_with_log` came to. `failed` is 0, 1 or None
# ("did not report", the spelling `general.log.digest` already uses); `error`
# is the exception the call raised, or None -- never what the command
# returned, which is for its python caller (see `run_with_log`). `prepend` is
# not a field: it is an input, and `run_in_parallel` binds it into the
# callback rather than carrying it through the worker and back.
CallOutcome = namedtuple("CallOutcome", "name failed error comlog")


def record(outcome, prepend=""):
    """
    ``record(outcome, prepend="")``

    Appends the :class:`CallOutcome` of a completed function.

    For internal use only.
    """

    global results

    results.append(outcome)

    with lock:
        see = " [log: %s]." % outcome.comlog if outcome.comlog else "."

        if outcome.failed is None:
            print("%s%s did not complete%s" % (prepend, outcome.name, see))
        elif outcome.failed:
            print("%s%s failed%s" % (prepend, outcome.name, see))
        else:
            print("%s%s finished successfully%s" % (prepend, outcome.name, see))


def record_future(future, name=None, prepend=""):
    if future.exception() is not None:
        print("Unhandled exception")
        print(future.exception())
        # the worker itself died -- a BrokenProcessPool, an OOM kill, a
        # pickling failure, or a raise from the lines of `run_with_log`
        # outside its try -- so there is no outcome to take. This used to
        # print and append nothing, which dropped the call from the digest,
        # from the status record and from the failure count: a run in which a
        # session never executed reported success and exited 0.
        record(CallOutcome(name, None, future.exception(), None), prepend)
    else:
        record(future.result(), prepend)


def _drop_run_parameters(function, args):
    """
    Drop the run-level parameters the command itself does not take.

    ``--logging``, ``--logfolder``, ``--scheduler`` and the rest steer how
    qunex runs a command, not what the command does, so reaching the callable
    is a TypeError. Functions with a ``**kwargs`` catch-all keep them: for
    those the pass-through is deliberate (``run_recipe`` threads ``eargs``
    this way).

    Note that this is never reached on a scheduler run: ``run_through_scheduler``
    strips ``--scheduler`` from the call it re-issues, and the paths that use it
    return before this one.
    """
    import qx_utilities.general.commands_support as gcs

    accepted = inspect.signature(function).parameters
    if any(p.kind == inspect.Parameter.VAR_KEYWORD for p in accepted.values()):
        return

    for extra in gcs.extra_parameters:
        if extra in args and extra not in accepted:
            del args[extra]


def run_with_log(
    function, args=None, run=None, name=None, prepend="", tags=None, tee=True
):
    """
    ``run_with_log(function, args=None, run=None, name=None, prepend="", tags=None, tee=True)``

    Runs a function, capturing everything it prints into a comlog and
    recording the call and its outcome in the run's runlog.

    Parameters:
        --function     The function to run.
        --args         The arguments to call it with.
        --run          The RunContext that owns this run's logs. When None the
                       function runs with its output going to the console only.
        --name         The name to report the call under [the function name].
        --prepend      The string to prepend to each line of progress report.
        --tags         The name parts of the comlog to open. When None no
                       comlog is opened and the output goes to the console.
        --tee          Whether the call's output also reaches the console.
                       False for a call submitted by `run_in_parallel`, whose
                       output would interleave with every other call's: it
                       goes to the call's own comlog only, which is announced
                       before the call starts and is line-buffered so it can
                       be followed live.

    A command that declares a ``_log`` parameter is handed a
    :class:`general.log.ReportLog` to report into. See §14.15 of the logging
    plan: the signature is the declaration, and the underscore is what keeps the
    parameter off the command line. Its report goes into the comlog live, and
    into the runlog as well when ``runlog_content`` is ``full`` or the call has
    no comlog to hold it.

    **A command fails by raising or by recording an error, never by what it
    returns.** Its return value is for a python caller -- a path, a count, a
    list of files -- and is not inspected here.

    Returns:
        a :class:`CallOutcome`. `error` is None unless the call raised, in
        which case it holds the exception; `failed` is 1 when the call raised
        or recorded an error, so a caller building a status does not have to
        infer it.

    For internal use only.
    """
    import qx_utilities.general.log as gl

    timestamp = datetime.now().strftime("%Y-%m-%d_%H.%M.%S.%f")

    if name is None:
        name = function.__name__

    comlog = run.comlog(*tags, timestamp=timestamp) if run and tags else None
    if comlog:
        comlog.open()

    if comlog and comlog.file:
        print_qunex_header(timestamp=timestamp, file=comlog.file)
        comlog.write("#\n")
        with lock:
            print(
                prepend
                + "started running %s at %s, track progress in %s"
                % (name, str(datetime.now()).split(".")[0], comlog.path)
            )
    else:
        with lock:
            print(print_qunex_header(timestamp=timestamp))
            print("#")
            print(
                prepend
                + "started running %s at %s" % (name, str(datetime.now()).split(".")[0])
            )

    # everything the command prints from here on goes into the comlog -- and,
    # unless the call is one of several running at once, to the console as
    # well; the streams are restored however the block exits
    with comlog.capture_stdout(tee=tee) if comlog else contextlib.nullcontext():
        with lock:
            print(
                "call: gmri %s %s\n-----------------------------------------"
                % (
                    function.__name__,
                    " ".join(['%s="%s"' % (k, v) for (k, v) in args.items()]),
                )
            )

        # the log the command reports into, built here so that it echoes into
        # the tee installed above (and never crosses a process boundary: a
        # parallel run pickles `args`, and sys.stdout does not pickle). It is
        # passed only to a callable that declares `_log`, which is how a
        # command opts in; the rest run exactly as they did before.
        log = gl.log_or_console(None)
        takes_log = "_log" in inspect.signature(function).parameters

        # the call's outcome is the exception it raised and the errors it
        # recorded -- never its return value. A command returns whatever is
        # useful to a python caller (a path, a count, a list of files, True),
        # and reading that as a status made a successful `backup_files` an
        # error and a no-op `remove_qunex_metadata` a success.
        error = None

        try:
            _drop_run_parameters(function, args)
            function(**args, **({"_log": log} if takes_log else {}))
        except ge.CommandError as e:
            with lock:
                print(ge.report_command_error(name, e))
            error = e
        except ge.CommandNull as e:
            with lock:
                print(ge.report_command_null(name, e))
            error = e
        except ge.CommandFailed as e:
            with lock:
                print(ge.report_command_failed(name, e))
            error = e
        except Exception as e:
            with lock:
                print("\n\nERROR")
                print(traceback.format_exc())
            error = e

        with lock:
            print(
                "\n-----------------------------------------\nFinished at %s"
                % (datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
            )

        # a command that took the log has a report to close; one that did not
        # recorded nothing, so there is nothing to write and nothing to derive
        # the count from. `failed` is the exception *or* a recorded error --
        # the error count is an additional source of failure, not a substitute.
        report = None
        failed = 1 if error else 0
        if log.text:
            log.finish(
                str(error) if error else "completed",
                failed=1 if error else None,
                name=name,
            )
            report = log.text
            failed = log.status[2]

        if not failed:
            print(f"\n---> Successful completion of task at {datetime.now()}")

    comlogname = comlog.close(status="error" if failed else "done") if comlog else None

    # record the call in the run's runlog -- one runlog per run, so this
    # appends to the file the RunContext opened rather than creating its own.
    # RunContext.write no-ops when the run has no runlog, which is what keeps
    # a run the settings gave no runlog from growing one here.
    if run:
        command, _, session = name.partition(": ")
        # the run's header already spelled the call; only a per-session call
        # is worth echoing again, since its arguments differ from the run's
        entry = gl.call_echo(command, args, session) + "\n" if session else name
        status = (
            "ERROR running %s" % name
            if failed
            else f"---> Successful completion of task at {datetime.now()}"
        )
        # the status line names the comlog in both modes: under `manifest` it is
        # the only pointer to what the command actually said
        if comlogname:
            status += " [log: %s]" % comlogname

        # `runlog_content` decides whether the report goes here as well as into
        # the comlog, where the same text already is -- and the setting is
        # clamped: a call with no comlog puts its report in the runlog whatever
        # the setting says, since `manifest` asks to avoid duplication and not
        # to discard the only copy.
        keep_report = report is not None and (
            comlogname is None or run.settings.runlog_content == "full"
        )
        body = "%s\n%s" % (report, status) if keep_report else status
        run.write("\n%s\n%s\n" % (entry, body))

    return CallOutcome(name, failed, error, comlogname)


def run_in_parallel(calls, cores=None, prepend="", run=None):
    """
    ``run_in_parallel(calls, cores=None, prepend="")``

    Runs functions specified in 'calls' in parallel utilizing all the available
    or the number of cores specified in 'cores'.

    INPUTS
    ======

    --calls        A list of dictionaries that specifies the commands to run.
                   It should consists of:

                   - name (the name of the command to run)
                   - function (the function to be run)
                   - args (the arguments to be passed to the function)
                   - tags (the name parts of the comlog to write the standard
                     output of the command to, or None for no comlog)

    --cores        The number of cores to utilize. If specified as None or
                   'all', all available cores will be utilized.
    --prepend      The string to prepend to each line of progress report.
    --run          The RunContext that owns this run's logs.

    EXAMPLE USE
    ===========

    ::

        run_in_parallel({'name': 'Sort dicom files', 'function': dicom.sort_dicom, 'args': {'folder': '.'}, 'tags': ['sort_dicom']}, cores=1, prepend=' ... ')
    """

    global results

    if cores is None or cores in ["all", "All", "ALL"]:
        cores = len(os.sched_getaffinity(0))
    else:
        try:
            cores = int(cores)
        except Exception:
            cores = 1

    results = []
    with ProcessPoolExecutor(max_workers=cores) as executor:
        for call in calls:
            future = executor.submit(
                run_with_log,
                call["function"],
                args=call["args"],
                run=run,
                name=call["name"],
                prepend=prepend,
                tags=call.get("tags"),
                tee=False,
            )
            # the name and `prepend` are bound here rather than returned by the
            # worker: both are inputs, and a worker that dies returns nothing
            # to take the name from
            future.add_done_callback(
                lambda f, n=call["name"], p=prepend: record_future(f, n, p)
            )

    return results


def check_files(test_folder, spec_file, fields=None, report=None):
    """
    ``check_files(test_folder, spec_file, fields=None, report=None)``

    Check the test_folder for presence of files as specified in spec_file, which
    lists files one per line with space delimited paths. Additionally an array
    of key-value pairs can be provided. If present every instance of {<key>}
    will be replaced by <value>. Where there might be two alternative options of
    results e.g. difference because of AP/PA direction, then the alternative is
    to be provided in the same line separated by a pipe '|'

    `report` is an open file handle -- the comlog of the call being checked --
    or None. It used to accept a path as well, and told the two apart with the
    Python 2 name ``types.FileType``; the only caller that ever passed one
    passed the path of a comlog it did not hold open, so the path form and its
    ``append`` companion are gone with it.
    """

    # --- the report goes to the caller's handle, when there is one

    if report:
        print(
            "\n#-----------------------------------------\n# Full file check report\n# . denotes file present\n# X denotes file absent\n",
            file=report,
        )

    # --- initial tests

    if not os.path.exists(test_folder):
        if report:
            print(
                "The folder to be tested does not exist: %s \nPlease check your settings and paths!"
                % (test_folder),
                file=report,
            )
            print(
                "\n#-----------------=== End Full File Report ===----------------------",
                file=report,
            )
        raise ge.CommandFailed(
            "check_files",
            "Folder to test does not exist",
            "The folder to be tested does not exist: %s" % (test_folder),
            "Please check your settings and paths!",
        )

    if not os.path.exists(spec_file):
        if report:
            print(
                "The specification file to test folder against does not exist: %s\nPlease check your settings and paths!"
                % (spec_file),
                file=report,
            )
            print(
                "\n#-----------------=== End Full File Report ===----------------------",
                file=report,
            )
        raise ge.CommandFailed(
            "check_files",
            "Specification file does not exist",
            "The specification file to test folder against does not exist: %s"
            % (spec_file),
            "Please check your settings and paths!",
        )

    # --- read the spec

    with open(spec_file, "r") as spec:
        files = spec.read()

    if fields:
        for key, value in fields:
            files = files.replace("{%s}" % (key), value)

    files = [
        [f.strip().split() for f in e.split("|")]
        for e in files.split("\n")
        if len(e) and not e.startswith("#")
    ]

    # --- test the files

    present = []
    missing = []
    for testfiles in files:
        file_missing = True
        for testfile in testfiles:
            test = [test_folder] + testfile
            tfile = os.path.join(*test)
            if os.path.exists(tfile):
                present.append(tfile)
                file_missing = False
                if report:
                    print(". " + tfile, file=report)
                break
        if file_missing:
            missing.append(tfile)
            if report:
                print("X " + tfile, file=report)

    if report:
        print(
            "\n#-----------------=== End Full File Report ===----------------------",
            file=report,
        )

    status = len(missing) == 0

    return status, present, missing


def print_and_log(*args, **kwargs):
    """
    ``print_and_log(*args, **kwargs)``

    Prints all that is given as nonpositional argument to the standard output.

    INPUTS
    ======

    --file         Prints to the file.
    --silent       Whether to not print to stdout.
    --end          How to end ['\n'].
    """

    silent = kwargs.get("silent", False)
    file = kwargs.get("file", None)
    end = kwargs.get("end", "\n")

    for element in args + (end,):
        if not silent:
            print(element, end=" ")
        if file:
            print(element, end=" ", file=file)


def underscore(s):
    s = s + "\n" + "".join(["=" for e in range(len(s))])
    return s


def plist(s):
    """
    plist(s)
    Processes the string, spliting it by the pipe "|" symbol, trimming
    any whitespace caracters from start or end of each resulting
    substring, and retuns an array of substrings of length more than 0.
    """
    s = s.split("|")
    s = [e.strip() for e in s]
    s = [e for e in s if len(e) > 0]
    return s


def pcslist(s):
    """
    pcslist(s)
    Processes the string, spliting it by the pipe "|", comma or space, trimming
    any whitespace caracters from start or end of each resulting substring, and
    retuns an array of substrings of length more than 0.
    """
    s = re.split(r" *, *| *\| *| +", s)
    s = [e.strip() for e in s]
    s = [e for e in s if len(e) > 0]
    return s


def link_or_copy(source, target, _log=None, status=None, name=None, symlink=False):
    """
    Hard-link a file, falling back to a copy, and report the outcome.

    Parameters:
        source (str): path to the file to map.
        target (str): destination path.
        _log (ReportLog | None): report log; when given, the mapping outcome is
            noted in it. Spelled with the underscore because that is the one
            name a log parameter has in this tree -- a plain `log` in a
            registered command's signature would collide with the `--log`
            comlog-retention parameter.
        status (bool | None): running status carried through (defaults True).
        name (str | None): human readable name used in the report message.
        symlink (bool): create a symbolic link instead of a hard link.

    Returns:
        bool: the running status -- False when the file could not be mapped.
    """

    log = _log

    def note(level, message):
        if log is not None:
            getattr(log, level)(message)

    if status is None:
        status = True
    if name is None:
        name = "file"
    if os.path.exists(source):
        try:
            if os.path.exists(target):
                if os.path.samefile(source, target):
                    note("detail", f"{name} already mapped")
                    return status and True
                else:
                    os.remove(target)

            # link
            if not symlink:
                os.link(source, target)
            else:
                os.symlink(source, target)

            note("detail", f"{name} mapped")
            return status and True

        except Exception:
            try:
                shutil.copy2(source, target)
                note("detail", f"{name} copied")
                return status and True
            except Exception:
                note("error", f"{name} could not be copied, check permissions!")
                return False
    else:
        note(
            "error",
            f"{name} could not be copied, source file does not exist [{source}]!",
        )
        return False


def move_link_or_copy(
    source, target, action=None, r=None, status=None, name=None, prefix=None, lock=False
):
    """
    Map a file into place by moving, hard-linking or copying it.

    Parameters:
        source (str): path to the file to map.
        target (str): destination path.
        action (str | None): one of ``"move"``, ``"link"`` or ``"copy"``
            (defaults ``"link"``).
        r (str | None): report so far; when given, the outcome is appended and
            returned alongside the status.
        status (bool | None): running status carried through (defaults True).
        name (str | None): human readable name used in the report message
            (defaults to ``source``).
        prefix (str | None): prefix for the report message.
        lock (bool): serialise the mapping with a file lock to make it safe for
            concurrent callers.

    Returns:
        bool | tuple: the status when ``r`` is None, otherwise
        ``(status, report_with_outcome_appended)``.
    """
    if action is None:
        action = "link"
    if status is None:
        status = True
    if name is None:
        name = source
    if prefix is None:
        prefix = ""

    def report(rstatus, msg):
        if lock:
            fl.unlock(target)
        if r is None:
            return rstatus
        else:
            return rstatus, r + prefix + msg

    if os.path.exists(source):
        targetfolder = os.path.dirname(target)
        if not os.path.exists(targetfolder):
            io = fl.makedirs(targetfolder)
            if io:
                if io != "File exists":
                    return report(
                        False,
                        "ERROR: %s could not be %sed, target folder could not be created, check permissions! "
                        % (name, action),
                    )

        if lock:
            fl.lock(target)

        if action == "link":
            io = fl.link(source, target)
            if not io:
                return report(status, "%s mapped" % (name))
            elif io == "File exists":
                if os.path.samefile(source, target):
                    return report(status, "%s already mapped [%s]" % (name, target))
                else:
                    io = fl.remove(target)
                    if io and io != "No such file or directory":
                        return report(
                            False,
                            "ERROR: %s could not be %sed, existing file could not be removed, check permissions! "
                            % (name, action),
                        )
                    io = fl.link(source, target)
                    if not io:
                        return report(status, "%s mapped" % (name))
                    else:
                        action = "copy"
            else:
                action = "copy"

        if action == "copy":
            try:
                shutil.copy2(source, target)
                return report(status, "%s copied" % (name))
            except Exception:
                return report(
                    False, "ERROR: %s could not be copied, check permissions! " % (name)
                )

        if action == "move":
            try:
                shutil.move(source, target)
                return report(status, "%s moved" % (name))
            except Exception:
                return report(
                    False, "ERROR: %s could not be moved, check permissions! " % (name)
                )

        if action == "gzip":
            try:
                with open(source, "rb") as f_in, gzip.open(target, "wb") as f_out:
                    shutil.copyfileobj(f_in, f_out)
                return report(status, "%s copied and gzipped" % (name))
            except Exception:
                return report(
                    False,
                    "ERROR: %s could not be copied and gzipped, check permissions! "
                    % (name),
                )

    else:
        return report(
            False,
            "WARNING: %s could not be %sed, source file either does not exist or can not be accessed [%s]! "
            % (name, action, source),
        )


def create_session_file(command, sfolder, session, subject, overwrite, prefix=""):
    """
    ``create_session_file(command, sfolder, session, subject, overwrite, prefix)``

    Creates the generic, non pipeline specific, session file.
    """

    # open fifle
    sfile = os.path.join(sfolder, "session.txt")
    if os.path.exists(sfile):
        if overwrite == "yes" or overwrite is True:
            os.remove(sfile)
            print(prefix + "---> removed existing session.txt file")
        else:
            raise ge.CommandFailed(
                command,
                "session.txt file already present!",
                "A session.txt file alredy exists [%s]" % (sfile),
                "Please check or set parameter 'overwrite' to 'yes' to rebuild it!",
            )

    sout = open(sfile, "w")
    print_qunex_header(file=sout)
    print("#", file=sout)
    print("session:", session, file=sout)
    print("subject:", subject, file=sout)

    # bids
    bfolder = os.path.join(sfolder, "bids")
    if os.path.exists(bfolder):
        print("bids:", bfolder, file=sout)

    # nii
    nfolder = os.path.join(sfolder, "nii")
    if os.path.exists(bfolder):
        print("raw_data:", nfolder, file=sout)

    # hcp
    hfolder = os.path.join(sfolder, "hcp")
    print("hcp:", hfolder, file=sout)

    # empty line
    print(file=sout)

    # return
    return sout


def get_qunex_version():
    """
    Returns the version of currently used QuNex suite.
    """

    # open the version file and read its contents
    with open(
        os.path.join(os.environ["TOOLS"], os.environ["QUNEXREPO"], "VERSION.md"), "r"
    ) as f:
        version = f.read().strip()

    return version
