# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Environment variables:
# 
# GITLAB_QUNEX_TOKEN: A group access token with `read_repository` git clone permission for qunex, qunex.wiki, and library
# QUNEXMCOMMAND: ?
#
# Note: GitLab tokens can only have a maximum lifetime of 365 days. 


# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      - qx_library/etc/docs/_extras/bash/pre_build.sh

# Sphinx build configuration
sphinx:
   configuration: qx_library/etc/docs/conf.py
   fail_on_warning: true

# The Python PyPi requirements required to build your docs
python:
   install:
   - requirements: qx_library/etc/docs/_extras/requirements.txt

# Token has permission to access both qunex and library
submodules:
  include: all
  recursive: true
