# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    post_checkout:
      - rm -rf qx_library # cannot clone into existing folder
      # TODO: replace "<replace_with_actual_token>" with the actual repo token
      # TODO: remove "-b develop" option to use master branch
      - git clone -b develop https://token:<replace_with_actual_token>@gitlab.qunex.yale.edu/qunex/library.git qx_library
    pre_build:
      - qx_library/etc/docs/_extras/bash/pre_build.sh

# Sphinx build configuration
sphinx:
   configuration: qx_library/etc/docs/conf.py

# The Python PyPi requirements required to build your docs
python:
   install:
   - requirements: qx_library/etc/docs/_extras/requirements.txt

# Exclude submodules to suppress Read the Docs invalid submodule token error
submodules:
  exclude: all
