##
# Dockerfile for MNAP
# MNAP code created by: Anticevic Lab, Yale University and Mind and Brain Lab, University of Ljubljana
# Maintainer of Dockerfile: Zailyn Tamayo, Yale University
##

##
# Tag: ztamayo/mnap_dep
# Dockerfile for dependencies needed to run MNAP suite
# Installs dependencies Python (+pkgs), R (+pkgs), Octave (+pkgs), Workbench, FreeSurfer 5.3-HCP, PALM, and Gradunwarp, FIX (removed), AFNI (removed)
##
##

## -- Dependency paths -- https://bitbucket.org/hidradev/mnaptools/wiki/Overview/Installation.md
#
## -----------------------------------------------------------------------------
#
#  $TOOLS                           # -- the base folder for the installation
#  ├── afni                         # Env. Variable = $AFNIDIR            # -- AFNI: Analysis of Functional NeuroImages (https://github.com/afni/afni)
#  ├── dcm2niix                     # Env. Variable = $DCM2NIIDIR         # -- dcm2niix (https://github.com/rordenlab/dcm2niix)
#  ├── fix                          # Env. Variable = $FIXICAFolder       # -- FIX ICA (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FIX/UserGuide)
#  ├── freesurfer-5.3-HCP           # Env. Variable = $FSDIR53HCP         # -- FreeSurfer (v5.3-HCP version for HCP-compatible data; http://ftp.nmr.mgh.harvard.edu/pub/dist/freesurfer/5.3.0-HCP/)
#  ├── freesurfer-<LATEST_VERSION>  # Env. Variable = $FSDIRLATEST        # -- FreeSurfer (v6.0 or later stable for all other data; https://surfer.nmr.mgh.harvard.edu/fswiki/DownloadAndInstall)
#  ├── fsl-<VERSION>                # Env. Variable = $FSLFolder          # -- FSL (v5.0.9 or above with GPU-enabled DWI tools; https://fsl.fmrib.ox.ac.uk/fsl/fslwiki)
#  ├── mnaptools                    # Env. Variable = $MNAPREPO           # -- All MNAP Suite repositories (https://bitbucket.org/hidradev/mnaptools)
#  ├── octave                       # Env. Variable = $OCTAVEDIR          # -- Octave v.4.2.1 or higher. If Octave is installed system-wide then a symlink is created here
#  ├── octavepkg                    # Env. Variable = $OCTAVEPKGDIR       # -- If Octave packages need manual deployment then the installed packages go here
#  ├── PALM/palm-<VERSION>          # Env. Variable = $PALMDIR            # -- PALM: Permutation Analysis of Linear Models (https://github.com/andersonwinkler/PALM)
#  ├── pylib                        # Env. Variable = $PYLIBDIR           # -- All python libraries and tools
#  │   ├── gradunwarp               # Env. Variable = $GRADUNWARPDIR      # -- HCP version of gradunwarp (https://github.com/Washington-University/gradunwarp)         
#  │   ├── nibabel                  # Env. Variable = $NIBABELDIR         # -- NiBabel (http://nipy.org/nibabel/)
#  │   └── pydicom                  # Env. Variable = $PYDICOMDIR         # -- pydicom (v1.1.0 or later; https://pydicom.github.io) 
#  └── workbench                    # Env. Variable = $HCPWBDIR           # -- Connectome Workbench (v1.0 or above; https://www.humanconnectome.org/software/connectome-workbench)
#
## -----------------------------------------------------------------------------

# Load mnap_os
FROM ztamayo/mnap_os:latest 

# Set $TOOLS path
ENV PATH="/opt" \
    TOOLS="/opt" \
    PATH="/opt:$PATH" \
    PYLIBDIR="/opt/pylib" \
    PATH="/opt/pylib:$PATH" \
    NIBABELDIR="/opt/pylib/nibabel" \
    PATH="/opt/pylib/nibabel:$PATH" \
    PYDICOMDIR="/opt/pylib/pydicom" \
    PATH="/opt/pylib/pydicom:$PATH"

# Run yum update
RUN yum clean all && \
# Install Python 2.7
    echo "Installing Python 2.7.14..." && \
    mkdir /tmp/Python-2.7.14 && \
    wget --progress=bar:force -O /tmp/Python-2.7.14.tgz https://www.python.org/ftp/python/2.7.14/Python-2.7.14.tgz && \
    tar -xzvf /tmp/Python-2.7.14.tgz -C /tmp/Python-2.7.14 --strip-components 1 && \
    cd /tmp/Python-2.7.14 && \
    ./configure --prefix=/usr/local --enable-optimizations --enable-unicode=ucs4 --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib" && \
    make -j$(nproc) && make altinstall && \
    alias python="python2.7" && \
    echo "alias python='python2.7'" >> ~/.bashrc && \
    echo "Installing pip for Python 2.7..." && \
    cd /usr/local/bin && \
    wget --progress=bar:force -O /usr/local/bin/get-pip.py https://bootstrap.pypa.io/get-pip.py && \
    python /usr/local/bin/get-pip.py && \
    alias pip="pip2.7" && \
    echo "alias pip='pip2.7'" >> ~/.bashrc && \
# Install Python packages
    echo "Installing Python packages..." && \
    pip install numpy pydicom scipy nibabel && \
# Install R
    echo "Installing R..." && \
    yum install -y R && \
    pip install rpy2==2.8.6 && \
# Install R package
    echo "Installing R packages..." && \
    echo "r <- getOption('repos'); r['CRAN'] <- 'http://cran.us.r-project.org'; options(repos = r);" > ~/.Rprofile && \
    Rscript -e "install.packages('ggplot2')"

# Install Octave 4.2.1
RUN echo "Installing Ocatve 4.2.1..." && \
    export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk && \
    mkdir -p /opt/Octave && \
    cd /opt/Octave && \
    git clone https://github.com/ztamayo/octave-enable64.git && \
    cd octave-enable64 && \
    scl enable devtoolset-3 -- make -j$(nproc) && \
    alias octave="/usr/local/bin/octave" && \
    echo "alias octave='/usr/local/bin/octave'" >> ~/.bashrc && \
# Install Octave packages
    echo "Installing Octave packages..." && \
    octave --no-gui --eval "pkg install -verbose -forge general" && \
    octave --no-gui --eval "pkg install -verbose -forge control" && \
    octave --no-gui --eval "pkg install -verbose -forge image" && \
    octave --no-gui --eval "pkg install -verbose -forge nan" && \
    octave --no-gui --eval "pkg install -verbose -forge signal" && \
    octave --no-gui --eval "pkg install -verbose -forge io" && \
    octave --no-gui --eval "pkg install -verbose -forge statistics" && \
    octave --no-gui --eval "pkg install -verbose -forge miscellaneous" && \
    octave --no-gui --eval "pkg install -verbose -forge struct" && \
    octave --no-gui --eval "pkg install -verbose -forge optim" && \                                  
# Clear yum cache and other empty folders
    yum clean all && \
    rm -rf /var/lib/yum/lists/* /var/cache/yum/ /tmp/* /var/tmp/* /boot /media /mnt /srv && \
    rm -rf ~/.cache/pip
    
# Set dcm2niix path
ENV PATH="/opt/dcm2niix/bin:$PATH" 

# Install dcm2niix
RUN echo "Downloading dcm2niix..." && \
    mkdir -p /tmp/dcm2niix && \
    wget --progress=bar:force -O /tmp/dcm2niix.tar.gz https://github.com/rordenlab/dcm2niix/archive/v1.0.20170624.tar.gz && \
    tar -xzvf /tmp/dcm2niix.tar.gz -C /tmp/ --strip-components 1 && \
    cd /tmp && \
    cmake -DUSE_OPENJPEG=ON . && \
    mkdir -p /opt/dcm2niix && \
    make -j$(nproc) && \
    mv bin/ /opt/dcm2niix && \
    cd / && \
    rm -rf /tmp/* && \
# Install FSL
    echo "Downloading FSL 5.0.9..." && \
    mkdir -p /opt/fsl-5.0.9 && \
    wget --progress=bar:force -O /tmp/fsl-5.0.9-centos6_64.tar.gz https://fsl.fmrib.ox.ac.uk/fsldownloads/fsl-5.0.9-centos6_64.tar.gz && \
    tar -xzvf /tmp/fsl-5.0.9-centos6_64.tar.gz -C /opt/fsl-5.0.9 --strip-components 1 && \
    rm /tmp/fsl-5.0.9-centos6_64.tar.gz && \
    rm -R /opt/fsl-5.0.9/data/first/

# Install FreeSurfer 6.0
RUN echo "Downloading FreeSurfer 6.0..." && \
    yum clean all && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    mkdir -p /opt/freesurfer-6.0 && \
    wget --progress=bar:force -O /tmp/recon-all-freesurfer6-3.min.tgz https://dl.dropbox.com/s/nnzcfttc41qvt31/recon-all-freesurfer6-3.min.tgz && \ 
    tar -xzvf /tmp/recon-all-freesurfer6-3.min.tgz -C /opt/freesurfer-6.0 --strip-components 1 && \
    rm /tmp/recon-all-freesurfer6-3.min.tgz && \
    rm -R /opt/freesurfer-6.0/trctrain && \
# Install FreeSurfer 5.3-HCP
    echo "Downloading FreeSurfer-5.3-HCP..." && \
    mkdir -p /opt/freesurfer-5.3-HCP/ && \
    wget --progress=bar:force -O /tmp/freesurfer-Linux-centos6_x86_64-stable-pub-v5.3.0-HCP.tar.gz ftp://ftp.nmr.mgh.harvard.edu/pub/dist/freesurfer/5.3.0-HCP/freesurfer-Linux-centos6_x86_64-stable-pub-v5.3.0-HCP.tar.gz && \
    tar -xzvf /tmp/freesurfer-Linux-centos6_x86_64-stable-pub-v5.3.0-HCP.tar.gz -C /opt/freesurfer-5.3-HCP/ --strip-components 1 && \
    rm /tmp/freesurfer-Linux-centos6_x86_64-stable-pub-v5.3.0-HCP.tar.gz && \
    rm -R /opt/freesurfer-5.3-HCP/trctrain

# Install PALM
RUN echo "Installing PALM..." && \
    mkdir -p /opt/PALM && \
    wget --progress=bar:force -O /tmp/palm-alpha112.tar.gz https://s3-us-west-2.amazonaws.com/andersonwinkler/palm/palm-alpha112.tar.gz && \
    tar -xzvf /tmp/palm-alpha112.tar.gz -C /opt/PALM && \
    rm /tmp/palm-alpha112.tar.gz && \
    cd /opt/PALM && \
    mv palm-alpha112/ palm-alpha112o/ && \
    cd /opt/PALM/palm-alpha112o/fileio/@file_array/private && \
    ./compile.sh && \
    mv file2mat.m x-file2mat.m && \
    mv init.m x-init.m && \
    cd /opt/PALM/palm-alpha112o/fileio/@gifti/private && \
    ./compile.sh && \
    mv zstream.m x-zstream.m && \
    cd /opt/PALM/palm-alpha112o/fileio/@xmltree/private && \
    cp /opt/PALM/palm-alpha112o/fileio/@file_array/private/compile.sh . && \
    cp /opt/PALM/palm-alpha112o/fileio/@file_array/private/Makefile.var . && \
    sed -e 's|^include ../../src/Makefile.var|include Makefile.var|' < Makefile > /tmp/Makefile && mv /tmp/Makefile Makefile && \
    ./compile.sh && \
    mv xml_findstr.m x-xml_findstr.m && \
# Git clone Gradunwarp
    mkdir -p /opt/pylib && \
    cd /opt/pylib && \
    echo "Downloading Gradunwarp..." && \
    git clone https://github.com/Washington-University/gradunwarp.git

WORKDIR /opt/pylib/gradunwarp/

# Install Gradunwarp
RUN echo "Installing Gradunwarp..." && \
    python setup.py install && \
# Download nibabel
    echo "Downloading nibabel..." && \
    wget --progress=bar:force -O /tmp/nibabel-1.2.0.dev.tar.gz https://github.com/downloads/ksubramz/gradunwarp/nibabel-1.2.0.dev.tar.gz && \
    tar -xzvf /tmp/nibabel-1.2.0.dev.tar.gz -C /opt/pylib && \
    rm /tmp/nibabel-1.2.0.dev.tar.gz 

WORKDIR /opt/pylib/nibabel-1.2.0.dev/

# Install nibabel
RUN echo "Installing nibabel..." && \
    python setup.py install && \
# Install Workbench
    echo "Downloading workbench..." && \
    wget --progress=bar:force -O /tmp/workbench-rh_linux64.zip https://ftp.humanconnectome.org/workbench/workbench-rh_linux64-v1.3.1.zip && \
    unzip /tmp/workbench-rh_linux64.zip -d /opt/ && \
    rm /tmp/workbench-rh_linux64.zip && \
    cd /opt/workbench/libs_rh_linux64 &&  \
    ln -s /usr/lib64/libz.so.1 && \
    cd /
# Install CUDA
RUN wget --progress=bar:force -O /tmp/cuda-repo-rhel7-7.5-18.x86_64.rpm http://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-repo-rhel7-7.5-18.x86_64.rpm && \
    rpm -i /tmp/cuda-repo-rhel7-7.5-18.x86_64.rpm && \
    yum clean all expire-cache &&\
    yum install -y cuda-7.5 && \
# Clear yum cache and other empty folders
    yum clean all && \
    rm -rf /var/lib/yum/lists/* /var/cache/yum/ /tmp/* /var/tmp/* /boot /media /mnt /srv && \
    rm -rf ~/.cache/pip

# Create Octave Sym Links
# Link octave install to /usr/bin
RUN ln -fs /usr/local/bin/octave-4.2.1 /usr/bin/octave && \
    ln -fs /usr/local/bin/octave-config-4.2.1 /usr/bin/octave-config && \
    ln -fs /usr/local/bin/octave-cli-4.2.1 /usr/bin/octave-cli && \
    ln -fs /usr/local/bin/mkoctfile-4.2.1 /usr/bin/mkoctfile && \
# Link octave install to /opt/Octave
    ln -fs /usr/local/bin/octave-4.2.1 /opt/Octave && \
    ln -fs /usr/local/bin/octave-config-4.2.1 /opt/Octave && \
    ln -fs /usr/local/bin/octave-cli-4.2.1 /opt/Octave && \
    ln -fs /usr/local/bin/mkoctfile-4.2.1 /opt/Octave && \
# Create directory in $TOOLS for octave packages and libraries and add sym links
    mkdir -p /opt/octavepkg && \
    ln -fs /usr/local/share/octave/packages /opt/octavepkg && \
    mkdir -p /opt/olib && \
    ln -fs /bin/epstool /opt/olib && \
    ln -sf /bin/fig2dev /opt/olib && \
    ln -sf /bin/pstoedit /opt/olib && \
    ln -sf /usr/bin/hdf5 /opt/olib && \
# Set up Python Sym Links
    ln -fs /usr/local/bin/python2.7 /opt/python && \
    mkdir -p /opt/pylib/lib/python2.7 && \
    mkdir -p /opt/pylib/lib64/python2.7 && \
    ln -fs /usr/lib/python2.7/site-packages /opt/pylib/lib/python2.7 && \
    ln -fs /usr/lib64/python2.7/site-packages /opt/pylib/lib64/python2.7 && \
    ln -fs /usr/lib/python2.7/site-packages/pydicom /opt/pylib/pydicom && \
    ln -fs /usr/lib/python2.7/site-packages/nibabel /opt/pylib/nibabel


CMD ["bash"]


# Install FIX
#RUN wget --progress=bar:force -O /tmp/fix.tar.gz http://www.fmrib.ox.ac.uk/~steve/ftp/fix.tar.gz && \
#    tar -xzvf /tmp/fix.tar.gz -C /opt && \
#    rm /tmp/fix.tar.gz

# Install AFNI
#ENV PATH="/opt/afni-latest:$PATH" \
#    AFNI_PLUGINPATH="/opt/afni-latest"
#RUN apt-get update -qq && \
#    apt-get install -y -q --no-install-recommends \
#           ed \
#           gsl-bin \
#           netpbm \
#           xfonts-base \
#           xvfb && \
#    apt-get clean && \
#    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
#    curl -sSL --retry 5 -o /tmp/toinstall.deb http://mirrors.kernel.org/debian/pool/main/libx/libxp/libxp6_1.0.2-2_amd64.deb && \
#    dpkg -i /tmp/toinstall.deb && \
#    rm /tmp/toinstall.deb && \
#    curl -sSL --retry 5 -o /tmp/toinstall.deb http://mirrors.kernel.org/debian/pool/main/libp/libpng/libpng12-0_1.2.49-1%2Bdeb7u2_amd64.deb && \
#    dpkg -i /tmp/toinstall.deb && \
#    rm /tmp/toinstall.deb && \
#    apt-get install -f && \
#    apt-get clean && \
#    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
#    gsl2_path="$(find / -name 'libgsl.so.19' || printf '')" && \
#    if [ -n "$gsl2_path" ]; then && \
#         ln -sfv "$gsl2_path" "$(dirname $gsl2_path)/libgsl.so.0"; && \
#    fi && \
#    ldconfig && \
#    echo "Downloading AFNI..." && \
#    mkdir -p /opt/afni-latest && \
#    wget --progress=bar:force -O /tmp/linux_openmp_64.tgz https://afni.nimh.nih.gov/pub/dist/tgz/linux_openmp_64.tgz 
#RUN tar -xzvf /tmp/linux_openmp_64.tgz -C /opt/afni-latest --strip-components 1 && \
#    rm /tmp/linux_openmp_64.tgz
