##
# CentOS 7 Dockerfile for MNAP
# MNAP code created by: Anticevic Lab, Yale University and Mind and Brain Lab, University of Ljubljana
# Maintainer of Dockerfile: Zailyn Tamayo, Yale University
##

##
# Tag: ztamayo/mnap_os:latest
# Base OS Dockerfile with ContOS deployed needed to run MNAP suite and dependencies
##

##
# Build:
# docker build -t ztamayo/mnap_os:latest .
##

##
# Create:
# docker container run -it --name mnap_os ztamayo/mnap_os
##

##
# Connect with bash
# docker exec -it mnap_os bash
##

# Pull base image
FROM centos:7

# Update CentOS 7
RUN yum update -y && yum upgrade -y && \
# Install EPEL Repository
    yum install -y epel-release && \
# Install packages
    yum install -y yum-utils \
                   bzip2 \
                   ca-certificates \
                   curl \
                   unzip \
                   cmake \
                   gcc \
                   gcc-c++ \
                   git \
                   make \
                   pigz \
                   wget \
                   vim \
                   bc \
                   file \
                   perl \
                   tcsh \
                   wget \
                   tmux \
                   patch \
                   centos-release-scl-rh \
                   qt5-qtbase-devel \
                   mesa-libOSMesa-devel \
                   gl2ps-devel \
                   qhull-devel \
                   java-1.8.0-openjdk-devel \
                   qt-devel \
                   libcurl-devel \
                   freetype-devel \
                   bzip2-devel \
                   atlas-devel \
                   libsndfile-devel \
                   portaudio-devel \
                   GraphicsMagick-c++-devel \
                   lapack64-devel \
                   lapack64 \
                   libblas-dev \
                   libatlas-dev \
                   liblapack-dev \
                   freeglut-devel \
                   gnuplot \
                   fltk-devel \
                   readline-devel \
                   qrupdate-devel \
                   hdf5-devel \
                   fftw-devel \
                   libstdc++-static \
                   glpk-devel \
                   pcre-devel \
                   octave-devel \
                   systemd \
                   units \
                   ghostscript \
                   python-devel \
                   openssl-devel \
                   zlib-devel && \
# Install REMI Repository
     wget --progress=bar:force -O /tmp/remi-release-7.rpm http://rpms.famillecollet.com/enterprise/remi-release-7.rpm && \
     rpm -Uvh /tmp/remi-release-7.rpm && \
# Fix for an Octave 4.2.1 error
    ln -s /usr/lib64/atlas/libtatlas.so /usr/lib64/libatlas.so && \
# Install devtoolset-6-gcc rpm package
    yum --enablerepo=centos-sclo-rh-testing install -y devtoolset-6-gcc && \
    yum --enablerepo=epel-testing install -y plotutils && \
    yum --enablerepo=remi install -y gd-last && \
# Manually install libraries needed for Octave
    wget --progress=bar:force -O /tmp/transfig-3.2.5d-13.el7.x86_64.rpm http://mirror.centos.org/centos/7/os/x86_64/Packages/transfig-3.2.5d-13.el7.x86_64.rpm  && \
    rpm -i /tmp/transfig-3.2.5d-13.el7.x86_64.rpm  && \
    rm -f /tmp/transfig-3.2.5d-13.el7.x86_64.rpm && \
    wget --progress=bar:force -O /tmp/libEMF-1.0.4-1.el6.x86_64.rpm http://mirror.centos.org/centos/6/os/x86_64/Packages/libEMF-1.0.4-1.el6.x86_64.rpm && \
    rpm -i /tmp/libEMF-1.0.4-1.el6.x86_64.rpm && \
    rm -f /tmp/libEMF-1.0.4-1.el6.x86_64.rpm && \
    wget --progress=bar:force -O /tmp/glibc-2.28-4.fc29.x86_64.rpm http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/g/glibc-2.28-4.fc29.x86_64.rpm && \
    wget --progress=bar:force -O /tmp/glibc-common-2.28-4.fc29.x86_64.rpm http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/g/glibc-common-2.28-4.fc29.x86_64.rpm && \
    wget --progress=bar:force -O /tmp/glibc-langpack-en-2.28-4.fc29.x86_64.rpm http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/g/glibc-langpack-en-2.28-4.fc29.x86_64.rpm && \
    rpm -i /tmp/glibc-2.28-4.fc29.x86_64.rpm /tmp/glibc-langpack-en-2.28-4.fc29.x86_64.rpm /tmp/glibc-common-2.28-4.fc29.x86_64.rpm --force && \
    wget --progress=bar:force -O /tmp/libstdc++-8.2.1-2.fc29.x86_64.rpm http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/l/libstdc++-8.2.1-2.fc29.x86_64.rpm && \
    rpm -i /tmp/libstdc++-8.2.1-2.fc29.x86_64.rpm --force && \
    rm -f /tmp/libstdc++-8.2.1-2.fc29.x86_64.rpm && \
    wget --progress=bar:force -O /tmp/pstoedit-3.73-3.fc29.x86_64.rpm http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/p/pstoedit-3.73-3.fc29.x86_64.rpm && \
    rpm -i /tmp/pstoedit-3.73-3.fc29.x86_64.rpm && \
    rm -f /tmp/pstoedit-3.73-3.fc29.x86_64.rpm && \
# Clean cache and other empty folders
    yum clean all && \
    rm -rf /var/lib/yum/* /var/cache/yum/* /tmp/* /var/tmp/* /boot /media /mnt /srv && \
    rm -rf ~/.cache/pip && \
    chmod 777 /opt && chmod a+s /opt && \
# Install perlbrew and perl-5.16.3
    curl -k -L https://install.perlbrew.pl | bash && \
    echo "source ~/perl5/perlbrew/etc/bashrc" >> ~/.bashrc

ENV PATH="/root/perl5/perlbrew/bin:$PATH"
ENV PATH="~/perl5/perlbrew:$PATH"
ENV PATH="~/perl5/perlbrew/bin/perlbrew:$PATH"
ENV PATH="~/perl5/perlbrew/etc/bashrc:$PATH"
ENV PERLBREW_PERL="perl-5.16.3"

RUN perlbrew --notest install perl-5.16.3 -n --switch && \
    perlbrew clean && \
    perlbrew switch perl-5.16.3

CMD ["bash"]
