#
#~ND~FORMAT~MARKDOWN~
#~ND~START~
#
# ## COPYRIGHT NOTICE
#
# Copyright (C) 2015 Anticevic Lab, Yale University
# Copyright (C) 2015 MBLAB, University of Ljubljana
#
# ## AUTHORS(s)
#
# * Zailyn Tamayo, Department of Psychiatry, Yale University
#
# ## PRODUCT
#
#  Dockerfile
#
# ## LICENSE
#
# * The Dockerfile = the "Software"
# * This Software conforms to the license outlined in the MNAP Suite:
# * https://bitbucket.org/hidradev/mnaptools/src/master/LICENSE.md
#
# ## TODO
#
# ## DESCRIPTION:
#
# * This is a general docker generation script for the MNAP suite
#
# ## PREREQUISITE INSTALLED SOFTWARE
#
# * MNAP Suite and dependencies
#
# ## PREREQUISITE ENVIRONMENT VARIABLES
#
#
# ## PREREQUISITE PRIOR PROCESSING
#
#
#~ND~END~

##
# Tag: ztamayo/mnap_suite:latest
# Dockerfile for MNAP suite
# Sets environment for MNAP
##

# Define docker image location
FROM ztamayo/mnap_dep:latest

# Define where the mnaptools repo resides on the image
ADD . /opt/mnaptools
WORKDIR /opt/mnaptools

# Set Python path 
ENV PTYHONPATH="/usr/local/bin/python2.7:$PTYHONPATH"

# Set MNAP tools path
ENV TOOLS="/opt"

# Copy over FreeSurfer license
ADD library/etc/license.txt /opt/freesurfer-6.0/
ADD library/etc/license.txt /opt/freesurfer-5.3-HCP/


# Set environment
RUN chmod a+x /opt/mnaptools/library/etc/cs-wrapper.sh && \
    ln /opt/mnaptools/library/environment/mnap_environment.sh /etc/profile.d/mnap_environment.sh && \
# Set Octave as default
    touch ~/.mnapuseoctave && \
    cd matlab/gmri/\@gmrimage && \
    cp mri_ReadNIfTImx_Octave.cpp mri_ReadNIfTImx.cpp && \
    cp mri_SaveNIfTImx_Octave.cpp mri_SaveNIfTImx.cpp && \
    mkoctfile --mex -lz  mri_ReadNIfTImx.cpp g_nifti.c znzlib.c && \
    mkoctfile --mex -lz  mri_SaveNIfTImx.cpp g_nifti.c znzlib.c && \
    rm mri_ReadNIfTImx.cpp && \
    rm mri_SaveNIfTImx.cpp && \
    rm g_nifti.o && \
    rm znzlib.o && \
# Move libhdf5.so.8 to /opt/olib for Octave to compute BOLD
    cd /usr/lib64/ && \
    mkdir hdf5 && \
    mv libhdf5* hdf5/ && \
    export LD_LIBRARY_PATH=hdf5:$LD_LIBRARY_PATH && \
# This code to install libraries is needed in this section because mnap_dep updates libraries
# This reverts back to the libraries needed by FS
# Manually install libraries needed for FS run
     wget --progress=bar:force -O /tmp/hdf5-1.8.5.patch1-10.el6.x86_64.rpm http://dl.fedoraproject.org/pub/epel/6/x86_64/Packages/h/hdf5-1.8.5.patch1-10.el6.x86_64.rpm && \
#     rpm -ev --nodeps hdf5 && \
     rpm -i /tmp/hdf5-1.8.5.patch1-10.el6.x86_64.rpm --force && \
     wget --progress=bar:force -O /tmp/netcdf-4.1.1-3.el6.5.x86_64.rpm http://dl.fedoraproject.org/pub/epel/6/x86_64/Packages/n/netcdf-4.1.1-3.el6.5.x86_64.rpm && \
#     rpm -ev --nodeps netcdf && \
     rpm -i /tmp/netcdf-4.1.1-3.el6.5.x86_64.rpm && \
# Clean up binary package files
     rm /tmp/netcdf-4.1.1-3.el6.5.x86_64.rpm && \
     rm /tmp/hdf5-1.8.5.patch1-10.el6.x86_64.rpm && \
# Clean the environment and go to mnap folder
    yum clean all && \
    rm -rf /var/lib/apt/lists/* /var/cache/yum /tmp/* /var/tmp/* /boot /media /mnt /srv && \
    rm -rf ~/.cache/pip

CMD ["bash"]
