#
#~ND~FORMAT~MARKDOWN~
#~ND~START~
#
# ## COPYRIGHT NOTICE
#
# Copyright (C) 2015 Anticevic Lab, Yale University
# Copyright (C) 2015 MBLAB, University of Ljubljana
#
# ## AUTHORS(s)
#
# * Zailyn Tamayo, Department of Psychiatry, Yale University
#
# ## PRODUCT
#
#  Dockerfile
#
# ## LICENSE
#
# * The Dockerfile = the "Software"
# * This Software conforms to the license outlined in the MNAP Suite:
# * https://bitbucket.org/hidradev/mnaptools/src/master/LICENSE.md
#
# ## TODO
#
# ## DESCRIPTION:
#
# * This is a general docker generation script for the MNAP suite
#
# ## PREREQUISITE INSTALLED SOFTWARE
#
# * MNAP Suite and dependencies
#
# ## PREREQUISITE ENVIRONMENT VARIABLES
#
#
# ## PREREQUISITE PRIOR PROCESSING
#
#
#~ND~END~

##
# Tag: ztamayo/mnap_suite:latest
# Dockerfile for MNAP suite
# Sets environment for MNAP
##

# Define docker image location
FROM ztamayo/mnap_dep:latest

# Define where the mnaptools repo resides on the image
ADD . /opt/mnaptools
WORKDIR /opt/mnaptools

# Set Python path
ENV PYTHONPATH="${PYTONPATH}:/mnaptools" 
ENV PTYHONPATH="/usr/local/bin/:$PTYHONPATH"

# Set MNAP tools path
ENV TOOLS="/opt"

# Copy over FreeSurfer license
ADD library/etc/license.txt /opt/freesurfer-6.0/
ADD library/etc/license.txt /opt/freesurfer-5.3-HCP/

# Set environment & Set Octave as default & Clear apt cache and other empty folders
RUN echo "source /opt/mnaptools/library/environment/mnap_environment.sh" >> ~/.bashrc && \
    touch ~/.mnapuseoctave && \
    cd matlab/gmri/\@gmrimage && \
    cp mri_ReadNIfTImx_Octave.cpp mri_ReadNIfTImx.cpp && \
    cp mri_SaveNIfTImx_Octave.cpp mri_SaveNIfTImx.cpp && \
    mkoctfile --mex -lz  mri_ReadNIfTImx.cpp g_nifti.c znzlib.c && \
    mkoctfile --mex -lz  mri_SaveNIfTImx.cpp g_nifti.c znzlib.c && \
    rm mri_ReadNIfTImx.cpp && \
    rm mri_SaveNIfTImx.cpp && \
    rm g_nifti.o && \
    rm znzlib.o && \
# Clean the environment and go to mnap folder
    yum clean all && \
    rm -rf /var/lib/apt/lists/* /var/cache/yum /tmp/* /var/tmp/* /boot /media /mnt /srv && \
    rm -rf ~/.cache/pip

CMD ["bash"]
