"""
Movement and BOLD statistics reporting for ``create_stats_report``.

This replaces ``r/qx_utilities/bold_stats.R``. It reads the per-BOLD movement
correction parameters, the scrubbing flags and the image statistics that
``compute_bold_stats`` leaves in ``images/functional/movement``, appends the
group level reports, writes the per-BOLD fidl scrubbing snippets, and draws the
three movement plots.

It computes no scrubbing of its own. Which frames are bad is decided by
``img_compute_scrub.m`` and read back out of the ``.scrub`` file, exactly as the
R script did -- the two names that select a column, ``mov_fidl`` and
``mov_post``, are therefore ``.scrub`` column names and nothing else.

The module registers no command. ``create_stats_report`` in ``workflow.py`` owns
the option surface, the ``--test`` contract and the log; this is the work behind
it, and it is called only from there.
"""

# SPDX-FileCopyrightText: 2026 QuNex development team <https://qunex.yale.edu/>
#
# SPDX-License-Identifier: GPL-3.0-or-later

import fcntl
import os

import numpy as np

import qx_utilities.general.log as gl

# the six movement correction parameters, in the order the .dat file and every
# report column carries them: three translations in mm, three rotations in deg
PARAMETERS = ["dx", "dy", "dz", "X", "Y", "Z"]

# the .scrub columns that name a rejection criterion, in report order
CRITERIA = ["mov", "dvars", "dvarsme", "idvars", "idvarsme", "udvars", "udvarsme"]

MOVEMENT_HEADER = ["session", "run", "stat"] + PARAMETERS
SCRUBBING_HEADER = ["session", "run"] + CRITERIA + ["%" + e for e in CRITERIA]

# R's cat() writes seven significant digits, and the group reports have been
# accumulating in that format for years. Matching it keeps a report that spans
# old and new runs readable
DIGITS = "%.7g"


def _format(value):
    """Render one report value the way R's ``cat()`` did."""
    return DIGITS % value


def read_movement(path):
    """
    Read a ``<bold>_mov.dat`` file into an ``(nframes, 6)`` array.

    The frame column is dropped: it is a row number, and every consumer here
    counts rows instead. Values are zeroed to the first frame, which is what
    makes the movement traces comparable across runs.
    """
    data = np.loadtxt(path, comments="#", ndmin=2)

    if data.shape[1] != len(PARAMETERS) + 1:
        raise ValueError(f"expected {len(PARAMETERS) + 1} columns in {path}, found {data.shape[1]}")

    return data[:, 1:] - data[0, 1:]


def read_named(path):
    """
    Read a ``.scrub`` or ``.bstats`` file into ``{column: array}``.

    Both carry an uncommented header line and trail off into ``#sum`` and ``#%``
    summary lines, which are comments and are skipped.

    **The header line is not necessarily the first line.**
    ``general_write_table`` writes its `pre` block ahead of it, and
    ``general_compute_bold_stats`` uses that block for the QuNex provenance
    line and, in a ``.scrub``, the parameters the scrubbing was computed with.
    ``genfromtxt(names=True)`` takes the *first* line as the field names,
    stripping a leading comment marker rather than skipping the line, so on
    such a file it reads ``Generated by QuNex 1.5.0 on ...`` as six column
    names and then fails on every row. Skipping to the header line explicitly
    is what makes the two shapes read the same.
    """
    with open(path) as table:
        header = 0
        for line in table:
            if not line.lstrip().startswith("#"):
                break
            header += 1

    data = np.genfromtxt(path, names=True, comments="#", dtype=float, skip_header=header)

    return {name: np.atleast_1d(data[name]) for name in data.dtype.names}


def frame_to_frame(movement, radius):
    """
    Per-frame change in the movement parameters, plus framewise displacement.

    Returns ``(deltas, fd)``. The first row of ``deltas`` is zero, so that it
    lines up with the movement array frame for frame rather than being one
    shorter. Rotations are converted to mm at the given head radius before
    entering the displacement sum, but the returned deltas keep the degrees --
    the reports quote them in degrees, only ``fd`` uses the millimetres.
    """
    deltas = np.vstack([np.zeros(len(PARAMETERS)), np.diff(movement, axis=0)])

    rotation_mm = radius * np.tan(np.radians(deltas[:, 3:]))
    fd = np.abs(deltas[:, :3]).sum(axis=1) + np.abs(rotation_mm).sum(axis=1)

    return deltas, fd


def summary_rows(movement, deltas, fd):
    """
    The eight statistics rows written per BOLD, as ``(stat, [values])``.

    Seven describe the six movement parameters; ``frame_dspl`` describes the
    framewise displacement and so carries four values, not six. The report has
    always been ragged that way.

    ``mean``, ``sd`` and ``span`` describe the movement itself; ``max``, ``md``,
    ``med`` and ``md2_max`` describe the frame-to-frame change.
    """
    absolute = np.abs(deltas)

    return [
        ("mean", movement.mean(axis=0)),
        ("sd", movement.std(axis=0, ddof=1)),
        ("span", movement.max(axis=0) - movement.min(axis=0)),
        ("max", absolute.max(axis=0)),
        ("md", absolute.mean(axis=0)),
        ("med", np.median(absolute, axis=0)),
        # the denominator is the signed maximum, not the absolute one
        ("md2_max", absolute.mean(axis=0) ** 2 / deltas.max(axis=0)),
        ("frame_dspl", np.array([fd.mean(), np.median(fd), fd.max(), fd.std(ddof=1)])),
    ]


def scrubbing_row(flags):
    """
    Counts and percentages of rejected frames, one row per BOLD.

    ``flags`` is the parsed ``.scrub`` file. Percentages are quoted to one
    decimal, as they always have been -- they are for reading, not arithmetic.
    """
    nframes = len(flags["frame"])
    counts = [flags[name].sum() for name in CRITERIA]

    return [_format(e) for e in counts] + ["%.1f" % (e / nframes * 100) for e in counts]


def ignore_blocks(flags, criterion):
    """
    Run-length encode a ``.scrub`` column into ``(onset_frame, length)`` blocks.

    The onset is the index of the first rejected frame, counting from zero, so
    that multiplying by the TR gives its time. A run that is already open on the
    first frame, or still open on the last, is closed at the boundary.
    """
    rejected = flags[criterion]
    change = np.diff(rejected)

    # +1 converts a diff index to the index of the frame after the transition,
    # which is the first rejected frame of the block
    starts = list(np.flatnonzero(change == 1) + 1)
    ends = list(np.flatnonzero(change == -1) + 1)

    if rejected[0] == 1:
        starts.insert(0, 0)
    if rejected[-1] == 1:
        ends.append(len(rejected))

    return list(zip(starts, ends))


def write_fidl_snippet(path, tr, flags, criterion):
    """
    Write the fidl snippet listing the frames to ignore.

    A run with nothing rejected still gets a file, holding the TR line alone.
    Downstream, a missing snippet and an empty one are not the same thing.

    Every line ends in a tab, which is an artefact of how R wrote these -- the
    in-tree reader splits on whitespace and does not care. It is reproduced so
    that a snippet regenerated from unchanged data diffs clean against the one
    the R script left behind.
    """
    with open(path, "w") as f:
        print(_format(tr), "", sep="\t", file=f)

        for start, end in ignore_blocks(flags, criterion):
            print(_format(start * tr), _format(start - end), "", sep="\t", file=f)


def append_report(path, header, rows):
    """
    Append rows to a group report, holding an exclusive lock on it.

    Parallel sessions append to the same three files, so the write is locked.
    The lock is taken on the report itself rather than on a companion ``.lck``
    file: it is one fewer file to leave behind, and it lets the header decision
    be made inside the lock, where the file cannot appear under us between the
    check and the write.
    """
    with open(path, "a") as f:
        fcntl.flock(f, fcntl.LOCK_EX)
        try:
            if f.tell() == 0:
                print("\t".join(header), file=f)
            for row in rows:
                print("\t".join(row), file=f)
        finally:
            fcntl.flock(f, fcntl.LOCK_UN)


def _bold_files(folder, bold, boldname, tail):
    """The three inputs for one BOLD. Only the .dat is named without the tail."""
    return {
        "movement": os.path.join(folder, f"{boldname}{bold}_mov.dat"),
        "scrub": os.path.join(folder, f"{boldname}{bold}{tail}.scrub"),
        "stats": os.path.join(folder, f"{boldname}{bold}{tail}.bstats"),
    }


def _report_rows(session, run, movement, deltas, fd):
    return [
        [session, run, stat] + [_format(e) for e in values]
        for stat, values in summary_rows(movement, deltas, fd)
    ]


def report_movement_statistics(folder, bolds, session, reports, options, plot, *, _log=None):
    """
    Build the movement reports, fidl snippets and plots for one session.

    Args:
        folder (str): the session's ``images/functional/movement`` folder.
        bolds (list): BOLD numbers to process, as strings.
        session (str): session id, quoted in the reports and the plot titles.
        reports (dict): target paths keyed ``mov_mreport``, ``mov_preport`` and
            ``mov_sreport``. An empty path means that report is not wanted.
        options (dict): the command's options. Read here are ``mov_radius``,
            ``mov_fd``, ``mov_dvars``, ``mov_dvarsme``, ``mov_fidl``,
            ``mov_post``, ``mov_pref``, ``tr``, ``boldname`` and
            ``nifti_tail``.
        plot (str): root name for the plot files, empty to skip plotting. The
            caller decides this rather than reading ``mov_plot`` directly: it
            also turns plotting off when the figures are already there and
            ``--overwrite`` is not set.

    Returns:
        The number of BOLDs processed.

    Raises:
        ValueError: an input file is malformed, or a named criterion is not a
            column of the ``.scrub`` file.
    """
    log = gl.log_or_console(_log)

    boldname = options["boldname"]
    tail = options["nifti_tail"]
    radius = float(options["mov_radius"])
    tr = float(options["tr"])

    movement_rows, post_rows, scrubbing_rows = [], [], []
    plotted = []

    for bold in bolds:
        files = _bold_files(folder, bold, boldname, tail)
        run = f"{boldname}{bold}{tail}"

        log.detail(f"reading {os.path.basename(files['movement'])}")

        movement = read_movement(files["movement"])
        flags = read_named(files["scrub"])
        stats = read_named(files["stats"])

        if len(flags["frame"]) != len(movement):
            raise ValueError(
                f"{run}: {len(movement)} frames of movement data but "
                f"{len(flags['frame'])} rows of scrubbing data"
            )

        deltas, fd = frame_to_frame(movement, radius)

        if reports["mov_mreport"]:
            movement_rows += _report_rows(session, run, movement, deltas, fd)

        if reports["mov_preport"]:
            keep = _selection(flags, options["mov_post"], run)
            post_rows += _report_rows(session, run, movement[keep], deltas[keep], fd[keep])

        if reports["mov_sreport"]:
            scrubbing_rows.append([session, run] + scrubbing_row(flags))

        if options["mov_fidl"] != "none":
            _selection(flags, options["mov_fidl"], run)
            snippet = os.path.join(folder, f"{run}_scrub.fidl")
            write_fidl_snippet(snippet, tr, flags, options["mov_fidl"])
            log.detail(f"wrote {os.path.basename(snippet)}")

        plotted.append((run, movement, deltas, fd, flags, stats))

    for target, header, rows in [
        (reports["mov_mreport"], MOVEMENT_HEADER, movement_rows),
        (reports["mov_preport"], MOVEMENT_HEADER, post_rows),
        (reports["mov_sreport"], SCRUBBING_HEADER, scrubbing_rows),
    ]:
        if target and rows:
            append_report(target, header, rows)
            log.detail(f"appended {os.path.basename(target)}")

    if plot:
        # imported here, not at the top: matplotlib is not installed on a bare
        # checkout, and everything above this line has to work without it
        from qx_utilities.processing import mov_plots

        for name in mov_plots.plot_movement(folder, plotted, session, plot, options):
            log.detail(f"created {os.path.basename(name)}")

    return len(bolds)


def _selection(flags, criterion, run):
    """Frames to keep under a criterion, checking the column exists first."""
    if criterion == "none":
        return np.ones(len(flags["frame"]), dtype=bool)

    if criterion not in flags:
        raise ValueError(
            f"{run}: '{criterion}' is not a column of the scrubbing data "
            f"(have: {', '.join(e for e in flags if e != 'frame')})"
        )

    return flags[criterion] == 0
