#!/bin/bash
#
# SPDX-FileCopyrightText: 2021 QuNex development team <https://qunex.yale.edu/>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
#~ND~FORMAT~MARKDOWN~
#~ND~START~
#
# ## Author(s)
#
# Originally developed by Moises Hernandez & Stam Sotiropoulos (Oxford)
# Modified by Alan Anticevic for PBS and SLURM compatibility via QuNex code (07/01/2017)
#
# ## Product
#
#  Wrapper for bedpostX GPU
#
# ## Description 
#   
# This script, bedpostx_gpu.sh, implements gpu-based bedpostX
# 
# ## Prerequisite Installed Software
#
# * FSL with GPU binaries
#
# ## Prerequisite Environment Variables
#
#
# ### Expected Previous Processing
# 
# * The necessary input files are DWI data from previous processing
# * These data are stored in: "$StudyFolder/subjects/$CASE/hcp/$CASE/T1w/Diffusion/ 
#
#~ND~END~

Usage() {
    echo ""
    echo "This is a simplified version of the bedpostX gpu call to run interactively."
    echo ""
    echo "Usage: bedpostx <subject_directory> [options]"
    echo ""
    echo "expects to find bvals and bvecs in subject directory"
    echo "expects to find data and nodif_brain_mask in subject directory"
    echo "expects to find grad_dev in subject directory, if -g is set"
    echo ""
    echo "<options>:"
    echo "-n (number of fibres per voxel, default 3)"
    echo "-w (ARD weight, more weight means less secondary fibres per voxel, default 1)"
    echo "-b (burnin period, default 1000)"
    echo "-j (number of jumps, default 1250)"
    echo "-s (sample every, default 25)"
    echo "-model (Deconvolution model. 1: with sticks, 2: with sticks with a range of diffusivities (default), 3: with zeppelins)"
    echo "-g (consider gradient nonlinearities, default off)"
    echo ""
    echo ""
    echo "ALTERNATIVELY: you can pass on xfibres options onto directly bedpostx"
    echo " For example:  bedpostx <subject directory> --noard --cnonlinear"
    echo " Type 'xfibres --help' for a list of available options "
    echo " Default options will be bedpostx default (see above), and not xfibres default."
    echo ""
    echo "Note: Use EITHER old OR new syntax."
    exit 1
}

monitor(){
    cat <<EOM > ${bedpostxdir}/monitor
#!/bin/bash
nparts=0
if [ $njobs -eq 1 ]; then
#1 part (GPU) and several subparts
#voxels processed in each subpart are 12800 or more if the last one is less than 6400 (1 part less)
    nparts=\$(($nvox/12800))
    if [ \$nparts%12800 != 0 ];then 
        nparts=\$((\$nparts + 1)) 
    fi
    last_part=\$(($nvox-(((\$nparts-1))*12800)))
    if [ \$last_part -lt 6400 ];then 
        nparts=\$((\$nparts - 1)) 
    fi
else
    nparts=$njobs
fi

echo
echo "----- Bedpostx Monitor -----"
finished=0
lastprinted=0
havedad=2
while [ \$finished -eq 0 ] ; do
    nfin=0
    part=0
    errorFiles=\`ls ${bedpostxdir}/logs/*.e* 2> /dev/null \`
    for errorFile in \$errorFiles
    do
        if [ -s \$errorFile ]; then
            echo An error ocurred. Please check file \$errorFile
            kill -9 $$
            exit 1
        fi
    done
    while [ \$part -le \$nparts ];do
        if [ -e ${bedpostxdir}/logs/monitor/\$part ]; then
            nfin=\$((\$nfin + 1))
        fi
        part=\$((\$part + 1))
    done
    newmessages=\$((\$nfin - \$lastprinted))
    while [ "\$newmessages" -gt 0 ];do
        lastprinted=\$((\$lastprinted + 1))
        echo \$lastprinted parts processed out of \$nparts
        newmessages=\$((\$newmessages - 1))
    done
    if [ -f ${bedpostxdir}/xfms/eye.mat ] ; then
        finished=1
        echo "All parts processed"
    exit 
    fi
    if [ ! \$havedad -gt 0 ]; then
       exit 0
    fi
    if [ "x$SGE_ROOT" = "x" ]; then
        havedad=\`ps -e -o pid 2>&1| grep "$$\\b" | wc -l\`
    fi
    sleep 50;
done
EOM
    chmod +x ${bedpostxdir}/monitor
}

make_absolute(){
    dir=$1;
    if [ -d ${dir} ]; then
    OLDWD=`pwd`
    cd ${dir}
    dir_all=`pwd`
    cd $OLDWD
    else
    dir_all=${dir}
    fi
    echo ${dir_all}
}

[ "$1" = "" ] && Usage

subjdir=`make_absolute $1`
subjdir=`echo $subjdir | sed 's/\/$/$/g'`
shift

echo "---------------------------------------------"
echo "------------ BedpostX GPU Version -----------"
echo "---------------------------------------------"
echo ""
echo subjectdir is $subjdir
echo ""

bedpostxdir=`make_absolute $1`
shift
echo bedpostxdir is $bedpostxdir
echo ""

#parse option arguments
qsys=0
njobs=1
nfibres=3
fudge=1
burnin=1000
njumps=1250
sampleevery=25
model=2
gflag=0
other=""

while [ ! -z "$1" ]
do
    case "$1" in
        -n) nfibres=$2;shift;;
        -w) fudge=$2;shift;;
        -b) burnin=$2;shift;;
        -j) njumps=$2;shift;;
        -s) sampleevery=$2;shift;;
        -model) model=$2;shift;;
        -g) gflag=1;; 
        *) other=$other" "$1;;
    esac
    shift
done
opts="--nf=$nfibres --fudge=$fudge --bi=$burnin --nj=$njumps --se=$sampleevery --model=$model --cnonlinear$other"

# -------------------------------------------------------------------------------------------------
# -- Initial setup stage
# -------------------------------------------------------------------------------------------------

# - check that all required files exist

if [ ! -d $subjdir ]; then
    echo "subject directory $1 not found"
    exit 1
fi

if [ ! -e ${subjdir}/bvecs ]; then
    if [ -e ${subjdir}/bvecs.txt ]; then
        mv ${subjdir}/bvecs.txt ${subjdir}/bvecs
    else
        echo "${subjdir}/bvecs not found"
        exit 1
    fi
fi

if [ ! -e ${subjdir}/bvals ]; then
    if [ -e ${subjdir}/bvals.txt ]; then
        mv ${subjdir}/bvals.txt ${subjdir}/bvals
    else
        echo "${subjdir}/bvals not found"
        exit 1
    fi
fi

if [ `${FSLDIR}/bin/imtest ${subjdir}/data` -eq 0 ]; then
    echo "${subjdir}/data not found"
    exit 1
fi

if [ ${gflag} -eq 1 ]; then
    if [ `${FSLDIR}/bin/imtest ${subjdir}/grad_dev` -eq 0 ]; then
    echo "${subjdir}/grad_dev not found"
    exit 1
    fi
fi

if [ `${FSLDIR}/bin/imtest ${subjdir}/nodif_brain_mask` -eq 0 ]; then
    echo "${subjdir}/nodif_brain_mask not found"
    exit 1
fi

if [ -e ${bedpostxdir}/xfms/eye.mat ]; then
    echo "${subjdir} has already been processed: ${bedpostxdir}." 
    echo "Delete or rename ${bedpostxdir} before repeating the process."
    exit 1
fi

echo ""
echo "-- Making bedpostx directory structure"
echo ""

mkdir -p ${bedpostxdir}/
mkdir -p ${bedpostxdir}/diff_parts
mkdir -p ${bedpostxdir}/logs
mkdir -p ${bedpostxdir}/logs/logs_gpu
mkdir -p ${bedpostxdir}/logs/monitor
rm -f ${bedpostxdir}/logs/monitor/*
mkdir -p ${bedpostxdir}/xfms

echo ""
echo "-- Copying files to bedpostx directory"
echo ""

cp ${subjdir}/bvecs ${subjdir}/bvals ${bedpostxdir}
${FSLDIR}/bin/imcp ${subjdir}/nodif_brain_mask ${bedpostxdir}
if [ `${FSLDIR}/bin/imtest ${subjdir}/nodif` = 1 ] ; then
    ${FSLDIR}/bin/fslmaths ${subjdir}/nodif -mas ${subjdir}/nodif_brain_mask ${bedpostxdir}/nodif_brain
fi

# -------------------------------------------------------------------------------------------------
# -- Preprocessing stage
# -------------------------------------------------------------------------------------------------

# Split the dataset in parts 
echo ""
echo "-- Pre-processing stage"
echo ""

if [ ${gflag} -eq 1 ]; then
    pre_command="$bindir/bin/split_parts_gpu ${subjdir}/data ${subjdir}/nodif_brain_mask ${bedpostxdir}/bvals ${bedpostxdir}/bvecs ${subjdir}/grad_dev 1 $njobs ${bedpostxdir}"
else
    pre_command="$bindir/bin/split_parts_gpu ${subjdir}/data ${subjdir}/nodif_brain_mask ${bedpostxdir}/bvals ${bedpostxdir}/bvecs NULL 0 $njobs ${bedpostxdir}"
fi
$pre_command

nvox=`${FSLDIR}/bin/fslstats ${bedpostxdir}/nodif_brain_mask -V  | cut -d ' ' -f1 `

# -------------------------------------------------------------------------------------------------
# -- bedpostx_gpu setup stage
# -------------------------------------------------------------------------------------------------

echo ""
echo "-- Queuing parallel processing stage"
echo ""

[ -f ${bedpostxdir}/commands.txt ] && rm ${bedpostxdir}/commands.txt

monitor
if [ "x$SGE_ROOT" = "x" ]; then
    ${bedpostxdir}/monitor&
fi

part=0
while [ $part -lt $njobs ]
do
    partzp=`$FSLDIR/bin/zeropad $part 4`
    
    if [ ${gflag} -eq 1 ]; then
        gopts="$opts --gradnonlin=${bedpostxdir}/grad_dev_$part"
    else
        gopts=$opts
    fi

    echo "${bindir}/bin/xfibres_gpu --data=${bedpostxdir}/data_$part --mask=${bedpostxdir}/nodif_brain_mask -b ${bedpostxdir}/bvals -r ${bedpostxdir}/bvecs --forcedir --logdir=${bedpostxdir}/diff_parts/data_part_$partzp $gopts ${subjdir} $part $njobs $nvox" >> ${bedpostxdir}/commands.txt
    
    part=$(($part + 1))
done

# -------------------------------------------------------------------------------------------------
# -- bedpostx_gpu run stage
# -------------------------------------------------------------------------------------------------

# -- Run Locally
chmod +x ${bedpostxdir}/commands.txt
. ${bedpostxdir}/commands.txt

# -------------------------------------------------------------------------------------------------
# -- post processing stage
# -------------------------------------------------------------------------------------------------

echo ""
echo "-- Queuing post processing stage"
echo ""

echo "-- Merging parts"
echo ""

merge_parts_gpu --data=${subjdir}/data --mask=${bedpostxdir}/nodif_brain_mask -b ${bedpostxdir}/bvals -r ${bedpostxdir}/bvecs --forcedir --logdir=${bedpostxdir}/diff_parts $gopts $nvox $njobs ${subjdir}

fib=1
while [ $fib -le $nfibres ]
do
    ${FSLDIR}/bin/fslmaths ${bedpostxdir}/merged_th${fib}samples -Tmean ${bedpostxdir}/mean_th${fib}samples
    ${FSLDIR}/bin/fslmaths ${bedpostxdir}/merged_ph${fib}samples -Tmean ${bedpostxdir}/mean_ph${fib}samples
    ${FSLDIR}/bin/fslmaths ${bedpostxdir}/merged_f${fib}samples -Tmean ${bedpostxdir}/mean_f${fib}samples

    ${FSLDIR}/bin/make_dyadic_vectors ${bedpostxdir}/merged_th${fib}samples ${bedpostxdir}/merged_ph${fib}samples ${subjdir}/nodif_brain_mask ${bedpostxdir}/dyads${fib}
    if [ $fib -ge 2 ];then
    ${FSLDIR}/bin/maskdyads ${bedpostxdir}/dyads${fib} ${bedpostxdir}/mean_f${fib}samples
    ${FSLDIR}/bin/fslmaths ${bedpostxdir}/mean_f${fib}samples -div ${bedpostxdir}/mean_f1samples ${bedpostxdir}/mean_f${fib}_f1samples
    ${FSLDIR}/bin/fslmaths ${bedpostxdir}/dyads${fib}_thr0.05 -mul ${bedpostxdir}/mean_f${fib}_f1samples ${bedpostxdir}/dyads${fib}_thr0.05_modf${fib}
    ${FSLDIR}/bin/imrm ${bedpostxdir}/mean_f${fib}_f1samples
    fi

    fib=$(($fib + 1))
done

if [ `${FSLDIR}/bin/imtest ${bedpostxdir}/mean_f1samples` -eq 1 ]; then
    ${FSLDIR}/bin/fslmaths ${bedpostxdir}/mean_f1samples -mul 0 ${bedpostxdir}/mean_fsumsamples
    fib=1
    while [ $fib -le $nfibres ]
    do
      ${FSLDIR}/bin/fslmaths ${bedpostxdir}/mean_fsumsamples -add ${bedpostxdir}/mean_f${fib}samples ${bedpostxdir}/mean_fsumsamples
      fib=$(($fib + 1))
    done
fi

echo ""
echo "-- Removing intermediate files"
echo ""

if [ `${FSLDIR}/bin/imtest ${bedpostxdir}/merged_th1samples` -eq 1 ];then
    if [ `${FSLDIR}/bin/imtest ${bedpostxdir}/merged_ph1samples` -eq 1 ];then
        if [ `${FSLDIR}/bin/imtest ${bedpostxdir}/merged_f1samples` -eq 1 ];then
            rm -rf ${bedpostxdir}/diff_parts
            rm -rf ${bedpostxdir}/data*
            rm -rf ${bedpostxdir}/grad_dev*
        fi
    fi
fi

echo ""
echo "-- Creating identity xfm"
echo ""

xfmdir=${bedpostxdir}/xfms
echo 1 0 0 0 > ${xfmdir}/eye.mat
echo 0 1 0 0 >> ${xfmdir}/eye.mat
echo 0 0 1 0 >> ${xfmdir}/eye.mat
echo 0 0 0 1 >> ${xfmdir}/eye.mat

# -------------------------------------------------------------------------------------------------
# -- Finish things up
# -------------------------------------------------------------------------------------------------

echo ""
echo "-- Finished bedpostx_gpu"
echo ""
