#
#~ND~FORMAT~MARKDOWN~
#~ND~START~
#
# ## COPYRIGHT NOTICE
#
# Copyright (C) 2015 Anticevic Lab, Yale University
# Copyright (C) 2015 MBLAB, University of Ljubljana
#
# ## AUTHORS(s)
#
# * Zailyn Tamayo, Department of Psychiatry, Yale University
#
# ## PRODUCT
#
#  Dockerfile
#
# ## LICENSE
#
# * The Dockerfile = the "Software"
# * This Software conforms to the license outlined in the MNAP Suite:
# * https://bitbucket.org/hidradev/mnaptools/src/master/LICENSE.md
#
# ## TODO
#
# ## DESCRIPTION:
#
# * This is a general docker generation script for the MNAP suite
#
# ## PREREQUISITE INSTALLED SOFTWARE
#
# * MNAP Suite and dependencies
#
# ## PREREQUISITE ENVIRONMENT VARIABLES
#
#
# ## PREREQUISITE PRIOR PROCESSING
#
#
#~ND~END~

##
# Tag: ztamayo/mnap_suite:latest
# Dockerfile for MNAP suite
# Sets environment for MNAP
##

# Define docker image location
FROM ztamayo/mnap_dep:latest

# Define where the mnaptools repo resides on the image
#ADD . /opt/mnaptools
#WORKDIR /opt/mnaptools

# Set MNAP environment variables 
ENV PYTHONPATH="/usr/local/bin/python2.7:$PYTHONPATH" \
    TOOLS="/opt" \
    MNAPREPO="/opt/mnaptools" \
    OCTAVEBINDIR="/opt/octave/octave-latest/bin" \
    PALMDIR="/opt/palm/palm-latest-o" \
    WORKBENCHDIR="/opt/workbench/workbench-latest" \
    OCTAVEPKGDIR="/opt/octave/octavepkg"

# Git clone MNAP repositiory
RUN cd /opt && \
    git clone https://ztamayo:jqNNVL9GqnyRBVsSGWHh@bitbucket.org/hidradev/mnaptools.git && \
    cd mnaptools/ && \
    git clone https://ztamayo:jqNNVL9GqnyRBVsSGWHh@bitbucket.org/hidradev/connector.git && \
    git clone https://ztamayo:jqNNVL9GqnyRBVsSGWHh@bitbucket.org/hidradev/library.git && \
    git clone https://ztamayo:jqNNVL9GqnyRBVsSGWHh@bitbucket.org/hidradev/niutilities.git && \
    git clone https://ztamayo:jqNNVL9GqnyRBVsSGWHh@bitbucket.org/hidradev/matlab.git && \
    git clone https://ztamayo:jqNNVL9GqnyRBVsSGWHh@bitbucket.org/hidradev/hcpmodified.git && \
    git clone https://ztamayo:jqNNVL9GqnyRBVsSGWHh@bitbucket.org/hidradev/hcpextendedpull.git && \
# Set environment
    chmod a+x /opt/mnaptools/library/etc/cs-wrapper.sh && \
    echo "source /opt/mnaptools/library/environment/mnap_environment.sh" >> /etc/profile && \
    echo "TOOLS='/opt'" >> /etc/profile && \
    echo "export $TOOLS" >> /etc/profile && \
    ln /opt/mnaptools/library/environment/mnap_environment.sh /etc/profile.d/mnap_environment.sh && \
# Add .container file to the /opt folder
    touch /opt/.container && \
    touch /opt/.hcppipelines && \
# Copy over FreeSurfer license
    cp /opt/mnaptools/library/etc/license.txt /opt/freesurfer/freesurfer-6.0/ && \
    cp /opt/mnaptools/library/etc/license.txt /opt/freesurfer/freesurfer-5.3-HCP/ && \
# Set Octave as default
    touch ~/.mnapuseoctave && \
    cd matlab/gmri/\@gmrimage && \
    cp mri_ReadNIfTImx_Octave.cpp mri_ReadNIfTImx.cpp && \
    cp mri_SaveNIfTImx_Octave.cpp mri_SaveNIfTImx.cpp && \
    mkoctfile --mex -lz  mri_ReadNIfTImx.cpp g_nifti.c znzlib.c && \
    mkoctfile --mex -lz  mri_SaveNIfTImx.cpp g_nifti.c znzlib.c && \
    rm mri_ReadNIfTImx.cpp && \
    rm mri_SaveNIfTImx.cpp && \
    rm g_nifti.o && \
    rm znzlib.o && \
# Set location for Octave to read octaverc file
    rm /usr/local/share/octave/site/m/startup/octaverc && \
    rm /usr/local/share/octave/4.4.1/m/startup/octaverc && \
    cp /opt/mnaptools/library/.octaverc /usr/local/share/octave/site/m/startup/octaverc && \
    cp /opt/mnaptools/library/.octaverc /usr/local/share/octave/4.4.1/m/startup/octaverc && \
# Move libhdf5.so.8 to /opt/olib for Octave to compute BOLD
    cd /usr/lib64/ && \
    mkdir hdf5 && \
    mv libhdf5* hdf5/ && \
    export LD_LIBRARY_PATH=/usr/lib64/hdf5/:LD_LIBRARY_PATH && \
# This code to install libraries is needed in this section because mnap_dep updates libraries
# This reverts back to the libraries needed by FS
# Manually install libraries needed for FS run
    wget --progress=bar:force -O /tmp/hdf5-1.8.5.patch1-10.el6.x86_64.rpm http://dl.fedoraproject.org/pub/epel/6/x86_64/Packages/h/hdf5-1.8.5.patch1-10.el6.x86_64.rpm && \
    rpm -i /tmp/hdf5-1.8.5.patch1-10.el6.x86_64.rpm --force && \
    wget --progress=bar:force -O /tmp/netcdf-4.1.1-3.el6.5.x86_64.rpm http://dl.fedoraproject.org/pub/epel/6/x86_64/Packages/n/netcdf-4.1.1-3.el6.5.x86_64.rpm && \
    rpm -i /tmp/netcdf-4.1.1-3.el6.5.x86_64.rpm && \
# Clean up binary package files
    rm /tmp/netcdf-4.1.1-3.el6.5.x86_64.rpm && \
    rm /tmp/hdf5-1.8.5.patch1-10.el6.x86_64.rpm && \
# Octave testing on Singularity
    rm /opt/palm/palm-latest-o/fileio/@nifti/private/write_hdr_raw.m && \
    cp /opt/mnaptools/library/etc/write_hdr_raw.m /opt/palm/palm-latest-o/fileio/@nifti/private && \
# Install HCP Pipelines
    mkdir -p /opt/HCP/Pipelines && \
    wget --progress=bar:force -O /tmp/freesurfer_v6_latest.tar.gz https://github.com/Washington-University/HCPpipelines/archive/feature/freesurfer_v6_latest.tar.gz && \
    tar -xzvf /tmp/freesurfer_v6_latest.tar.gz -C /opt/HCP/Pipelines --strip-components=1 && \
    rm /tmp/freesurfer_v6_latest.tar.gz && \
    ln -sf /opt/HCP/gradient_coefficient_files/3TPrisma_coeff_AS82_trunc.grad /opt/HCP/Pipelines/global/config/3TPrisma_coeff_AS82_trunc.grad && \
    ln -sf /opt/HCP/gradient_coefficient_files/coeff_SC72C_Skyra.grad /opt/HCP/Pipelines/global/config/coeff_SC72C_Skyra.grad && \
    ln -sf /opt/HCP/gradient_coefficient_files/trunc.CMRR_7TAS_coeff_SC72CD.grad /opt/HCP/Pipelines/global/config/trunc.CMRR_7TAS_coeff_SC72CD.grad && \
    ln -sf /opt/HCP/gradient_coefficient_files/CMRR_3TPrisma_coeff_AS82_trunc.grad /opt/HCP/Pipelines/global/config/CMRR_3TPrisma_coeff_AS82_trunc.grad && \
    ln -sf /opt/HCP/gradient_coefficient_files/Prisma_3T_coeff_AS82.grad /opt/HCP/Pipelines/global/config/Prisma_3T_coeff_AS82.grad && \
# CUSTOM: recon-all.v6.hires
    cp /opt/HCP/Pipelines/FreeSurferCustomizations/recon-all.v6.hires /opt/freesurfer/freesurfer-6.0/bin/recon-all.v6.hires && \
    chmod 775 /opt/freesurfer/freesurfer-6.0/bin/recon-all.v6.hires && \
# CUSTOM: conf2hires
    cp /opt/HCP/Pipelines/FreeSurferCustomizations/conf2hires /opt/freesurfer/freesurfer-6.0/bin/conf2hires && \
    chmod 775 /opt/freesurfer/freesurfer-6.0/bin/conf2hires && \
# CUSTOM: longmc
    cp /opt/HCP/Pipelines/FreeSurferCustomizations/longmc /opt/freesurfer/freesurfer-6.0/bin/longmc && \
    chmod 775 /opt/freesurfer/freesurfer-6.0/bin/longmc && \    
    git clone https://github.com/Washington-University/HCPpipelinesRunUtils.git && \
# FS / FSL interaction
#     unset FSL_DIR && \
#     export FREESURFER_HOME="/opt/freesurfer/freesurfer-6.0" && \
#     mnap_envset && \ 
# Clean the environment and go to mnap folder
    yum clean all && \
    rm -rf /var/lib/apt/lists/* /var/cache/yum /tmp/* /var/tmp/* /boot /media /mnt /srv && \
    rm -rf ~/.cache/pip

# Set mnaptools as working directory
WORKDIR /opt/mnaptools

CMD ["bash"]
