#!/bin/bash
#
# SPDX-FileCopyrightText: 2021 QuNex development team <https://qunex.yale.edu/>
#
# SPDX-License-Identifier: GPL-3.0-or-later

Usage() {
    echo ""
    echo "auto_ptx <StudyFolder> <SessionId> <BpXFolder> [<std2diff> <diff2std>]"
    echo ""
    exit 1
}

[ "$3" = "" ] && Usage

StudyFolder=$1
SessionId=$2
BpxFolder=$3

InputDir=$StudyFolder/$SessionId/T1w/$BpxFolder
OutDir=${StudyFolder}/${SessionId}/MNINonLinear/Results/autoPtx
mkdir -p ${OutDir}

if [ "$4" == "" ]; then
    MNI_to_FA_warp=${StudyFolder}/${SessionId}/MNINonLinear/xfms/standard2acpc_dc.nii.gz
else
    MNI_to_FA_warp=$4
fi

if [ "$5" == "" ]; then
    FA_to_MNI_warp=${StudyFolder}/${SessionId}/MNINonLinear/xfms/acpc_dc2standard.nii.gz
else
    FA_to_MNI_warp=$5
fi

logDir=${OutDir}/logs
rm -rf $logDir
mkdir -p $logDir
execPath=`dirname $0`

cd ${InputDir}

structures=$QUNEXLIBRARYETC/auto_ptx/structure_list

listJobs=""

rm -f ${OutDir}/commands.txt

while read line ; do
    #echo $line
    struct=`echo $line | awk '{print $1}'`
    nseed=`echo $line | awk '{print $2}'`
    wallt=`echo $line | awk '{print $3}' | tr ':' ' '`
    hours=`echo $wallt | awk '{print $1}'`
    minutes=`echo $wallt | awk '{print $2}'`
    time=$(( 60 * hours + minutes ))
    echo "$execPath/track_subject_struct ${InputDir} $struct $nseed $MNI_to_FA_warp $FA_to_MNI_warp ${OutDir} $GPU_flag" >> ${OutDir}/commands.txt
done < $structures

chmod +x ${OutDir}/commands.txt
bash ${OutDir}/commands.txt	
