#!/usr/bin/env python
# encoding: utf-8

# SPDX-FileCopyrightText: 2021 QuNex development team <https://qunex.yale.edu/>
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""
``get_dicom_info.py``

The ``get_dicom_info`` command: prints the HCP relevant acquisition
parameters stored in a DICOM file.
"""

# Copyright (c) Grega Repovs. All rights reserved.

import os

import qx_utilities.general.exceptions as ge
from qx_utilities.dicom.dicom_info import read_dicom_base


def get_dicom_info(dicomfile=None, scanner="siemens"):
    """
    ``get_dicom_info dicomfile=<dicom_file> [scanner=siemens]``

    Inspect the specified DICOM file.

    ..  qx_command:
        type: utility

    Parameters:
        --dicomfile (str, ''):
            The path to the DICOM file to be inspected.

        --scanner (str, 'siemens'):
            The scanner on which the data was acquired, currently only
            "siemens" and "philips" are supported.

    Notes:
        The command inspects the specified DICOM file (dicomfile) for information
        that is relevant for HCP preprocessing and prints out the report.
        Specifically it looks for and reports the following information:

        - Institution
        - Scanner
        - Sequence
        - Session ID
        - Sample spacing
        - Bandwidth
        - Acquisition Matrix
        - Dwell Time
        - Slice Acquisition Order

        If the information can not be found or computed it is listed as 'undefined'.

        Currently only DICOM files generated by Siemens and Philips scanners are
        supported.

    Examples:
        ::

            qunex get_dicom_info dicomfile=ap308e727bxehd2.372.2342.42566.dcm
    """

    if dicomfile is None:
        raise ge.CommandError(
            "get_dicom_info", "No path to the dicom file was provided"
        )

    if not os.path.exists(dicomfile):
        raise ge.CommandFailed(
            "get_dicom_info",
            "DICOM file does not exist",
            "Please check path! [%s]" % (dicomfile),
        )

    if scanner not in ["siemens", "philips"]:
        raise ge.CommandError(
            "get_dicom_info",
            "Scanner not supported",
            "The specified scanner is not yet supported! [%s]" % (scanner),
        )

    d = read_dicom_base(dicomfile)
    ok = True

    print("\nHCP relevant information\n(dicom %s)\n" % (dicomfile))

    try:
        print("            Institution:", d[0x0008, 0x0080].value)
    except Exception:
        print("            Institution: undefined")

    try:
        print(
            "                Scanner:", d[0x0008, 0x0070].value, d[0x0008, 0x1090].value
        )
    except Exception:
        print("                Scanner: undefined")

    try:
        print("Magnetic field strength:", d[0x0018, 0x0087].value)
        tesla = float(d[0x0018, 0x0087].value)
    except Exception:
        print("Magnetic field strength: unknown")
        tesla = None

    try:
        print("               Sequence:", d[0x0008, 0x103E].value)
    except Exception:
        print("               Sequence: undefined")

    try:
        print("             Session ID:", d[0x0010, 0x0020].value)
    except Exception:
        print("             Session ID: undefined")

    if scanner == "siemens":
        try:
            print("         Sample spacing:", d[0x0019, 0x1018].value)
        except Exception:
            print("         Sample spacing: undefined")

        try:
            bw = d[0x0019, 0x1028].value
            print("               Bandwith:", bw)
        except Exception:
            print("               Bandwith: undefined")
            ok = False

        try:
            am = d[0x0051, 0x100B].value
            print("     Acquisition Matrix:", am)
            am = float(am.split("*")[0].replace("p", ""))
        except Exception:
            print("     Acquisition Matrix: undefined")
            ok = False

        if ok:
            dt = 1 / (bw * am)
            print("             Dwell Time:", dt)
        else:
            print("             Dwell Time: Could not compute, data missing!")

        try:
            sinfo = d[0x0029, 0x1020].value
            sinfo = sinfo.split("\n")
            for ln in sinfo:
                if "sSliceArray.ucMode" in ln:
                    for k, v in [
                        ("0x1", "Sequential Ascending"),
                        ("0x2", "Sequential Ascending"),
                        ("0x4", "Interleaved"),
                    ]:
                        if k in ln:
                            print("Slice Acquisition Order: %s" % (v))
        except Exception:
            print("Slice Acquisition Order: Unknown")

    # --- Philips data

    if scanner == "philips":
        try:
            print("        Repetition Time: %.2f" % (float(d[0x0018, 0x0080].value)))
        except Exception:
            try:
                print("        Repetition Time:", d[0x2005, 0x1030].value[0])
            except Exception:
                print("        Repetition Time: undefined")

        try:
            print("             Flip Angle:", d[0x2001, 0x1023].value)
        except Exception:
            print("             Flip Angle: undefined")

        try:
            print("       Number of Echoes:", d[0x2001, 0x1014].value)
        except Exception:
            print("       Number of Echoes: undefined")

        try:
            print("   Phase Encoding Steps:", d[0x0018, 0x0089].value)
        except Exception:
            print("   Phase Encoding Steps: undefined")

        try:
            print("      Echo Train Length:", d[0x0018, 0x0091].value)
            etl = float(d[0x0018, 0x0091].value)
        except Exception:
            print("      Echo Train Length: undefined")
            etl = None

        try:
            print("             EPI Factor:", d[0x2001, 0x1013].value)
        except Exception:
            print("             EPI Factor: undefined")

        try:
            print("        Water Fat Shift:", d[0x2001, 0x1022].value)
            wfs = float(d[0x2001, 0x1022].value)
        except Exception:
            print("        Water Fat Shift: undefined")
            wfs = None

        try:
            print("        Pixel Bandwidth:", d[0x0018, 0x0095].value)
        except Exception:
            print("        Pixel Bandwidth: undefined")

        try:
            print("   Acquisition Duration:", d[0x0018, 0x9073].value)
        except Exception:
            print("   Acquisition Duration: undefined")

        try:
            print("   Parallel Acquisition:", d[0x0018, 0x9077].value)
            if d[0x0018, 0x9077].value == "YES":
                try:
                    print(
                        "%23s: in plane: %.2f out of plane %.2f"
                        % (
                            d[0x0018, 0x9078].value,
                            d[0x0018, 0x9168].value,
                            d[0x0018, 0x9155].value,
                        )
                    )
                except Exception:
                    print("                 Factor: undefined")
        except Exception:
            print("   Parallel Acquisition: undefined")

        try:
            print(
                "                 Matrix: [%d, %d, %d]"
                % (
                    d[0x0028, 0x0010].value,
                    d[0x0028, 0x0011].value,
                    d[0x2001, 0x1018].value,
                )
            )
        except Exception:
            print("                 Matrix: undefined")

        try:
            print(
                "          Field of View: [%d, %d, %d]"
                % (
                    d[0x2005, 0x1074].value,
                    d[0x2005, 0x1076].value,
                    d[0x2005, 0x1075].value,
                )
            )
        except Exception:
            print("          Field of View: undefined")

        try:
            if tesla == 3:
                wfdiff = 3.35
                resfreq = 42.576
                dwelltime = 1 / (tesla * wfdiff * resfreq / wfs * etl)
                print("   Parallel Acquisition: undefined")
                print("    Estimated dwelltime: %.8f" % (dwelltime))
        except Exception:
            print("    Estimated dwelltime: unknown")

    # --- look for slice ordering info

    print
