#!/usr/bin/env python
# encoding: utf-8

# SPDX-FileCopyrightText: 2026 QuNex development team <https://qunex.yale.edu/>
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Guard against a stale spliced parser in ``bin/qunex_container``.

The container can not import QuNex — it runs on the login node, outside the
container — so it carries a generated copy of ``general/batch_io.py``. This test
re-splices from the current source and fails if the committed container
disagrees, the same arrangement ``test_registry_drift.py`` has with
``qx_commands.yaml``. The fix is always to run ``qunex build_qx_container`` and
commit the result.

The second test loads the container and exercises the spliced code, which is
also what proves the region is wired in rather than merely present.
"""

import importlib.util
from importlib.machinery import SourceFileLoader
from pathlib import Path

import qx_container_build

REPO_ROOT = Path(__file__).resolve().parents[2]
CONTAINER = REPO_ROOT / "bin" / "qunex_container"
BATCH_IO = REPO_ROOT / "python" / "qx_utilities" / "general" / "batch_io.py"

BATCH = """# Generated by QuNex
--hcp_brainsize: 150

---
id: S01
group: control
---
id: S02
group: patient
---
id: S03
group: control
"""


def load_container():
    # the container has no .py extension, so it needs its loader named
    loader = SourceFileLoader("qunex_container", str(CONTAINER))
    spec = importlib.util.spec_from_loader(loader.name, loader)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_committed_container_matches_batch_io():
    assert CONTAINER.exists(), f"missing {CONTAINER}"

    rebuilt = qx_container_build.render(CONTAINER.read_text(), BATCH_IO.read_text())

    assert rebuilt == CONTAINER.read_text(), (
        "the generated region in bin/qunex_container is out of date or has been "
        "hand edited — run `qunex build_qx_container` and commit."
    )


def test_the_container_resolves_and_filters(tmp_path):
    batchfile = tmp_path / "batch.txt"
    batchfile.write_text(BATCH)

    slist, header = load_container().resolve(
        batchfile=str(batchfile), sessions="S01,S02", filter="group:control"
    )

    assert [e["id"] for e in slist] == ["S01"]
    assert header == {"hcp_brainsize": "150"}
