#!/usr/bin/env python
# encoding: utf-8

# SPDX-FileCopyrightText: 2026 QuNex development team <https://qunex.yale.edu/>
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""
``general/batch_io`` — the batch file parser, the session selector and the
filter — and `resolve_sessions`, the QuNex wrapper over it in `general/core`.

The stdlib-only assertion is the point of the first test: `build_qx_container`
splices this module into `bin/qunex_container`, which runs on a login node in
the host python with no QuNex on the path. An import of anything else is not a
style problem there, it is a broken container. The same shape as
`test_log_is_a_leaf.py`, which pins `general/log` as an import leaf.
"""

import ast
import os
import sys
from pathlib import Path

import pytest

import qx_utilities.general.batch_io as bio
import qx_utilities.general.core as gc
from qx_utilities.general.exceptions import CommandFailed

BATCH_IO = (
    Path(__file__).resolve().parents[1] / "qx_utilities" / "general" / "batch_io.py"
)

BATCH = """# Generated by QuNex
_batch_header: yes
--hcp_brainsize: 150
--unzip: yes

---
id: S01
subject: S01
group: control
task: rest
raw_data: /data/S01
01: T1w
02: bold1:rest: nii.gz
---
id: S02
subject: S02
group: patient
task: rest
--hcp_brainsize: 170
_hcp_suffix: test
---
session: S03
subject: S03
group: patient
task: motor
---
subject: S04
group: control
"""


def write_batch(tmp_path, content=BATCH, name="batch.txt"):
    path = tmp_path / name
    path.write_text(content)
    return str(path)


# ------------------------------------------------------------------ stdlib only


def test_batch_io_imports_only_the_stdlib():
    imported = set()
    for node in ast.walk(ast.parse(BATCH_IO.read_text())):
        if isinstance(node, ast.Import):
            imported.update(a.name for a in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
            imported.add(node.module)
        elif isinstance(node, ast.ImportFrom) and node.level:
            imported.add("." * node.level + (node.module or ""))

    reaching = {e for e in imported if e.split(".")[0] not in sys.stdlib_module_names}

    assert reaching == set(), (
        "`general/batch_io` imports %s. It is spliced into `bin/qunex_container`, "
        "which runs with no QuNex and no site packages on the path — it may "
        "import nothing but the standard library." % sorted(reaching)
    )


# ---------------------------------------------------------------------- parsing


def test_read_batch_reads_the_header_and_the_sessions(tmp_path):
    records, header = bio.read_batch(write_batch(tmp_path))

    assert header == {"batch_header": "yes", "hcp_brainsize": "150", "unzip": "yes"}
    assert [e["id"] for e in records] == ["S01", "S02", "S03"]

    # id and session are filled in from each other, the record without either
    # is dropped
    assert records[2]["id"] == "S03"
    assert records[0]["session"] == "S01"


def test_read_batch_keeps_per_session_overrides(tmp_path):
    records, _ = bio.read_batch(write_batch(tmp_path))

    # a per session parameter keeps its prefix, a header one loses it
    assert records[1]["--hcp_brainsize"] == "170"
    assert records[1]["_hcp_suffix"] == "test"
    assert "--hcp_brainsize" not in records[0]


def test_read_batch_reads_the_image_data(tmp_path):
    records, _ = bio.read_batch(write_batch(tmp_path))

    assert records[0]["01"] == {"ima": "01", "name": "T1w"}
    assert records[0]["02"]["name"] == "bold1"
    assert records[0]["02"]["task"] == "rest"


def test_read_batch_raises_on_a_missing_file(tmp_path):
    with pytest.raises(bio.BatchError):
        bio.read_batch(str(tmp_path / "there-is-no-batch.txt"))


def test_read_batch_names_the_file_and_the_line_it_failed_on(tmp_path):
    broken = BATCH.replace("01: T1w", "c1: only:two")

    with pytest.raises(bio.BatchError) as e:
        bio.read_batch(write_batch(tmp_path, broken))

    assert "batch.txt" in str(e.value)
    assert "c1: only:two" in str(e.value)


def test_read_list_reads_a_list_file(tmp_path):
    path = tmp_path / "sessions.list"
    path.write_text(
        "# a list file\n"
        "session id: S01\n"
        "file: /data/S01/a.nii.gz\n"
        "file: /data/S01/b.nii.gz\n"
        "roi: /data/S01/roi.nii.gz\n"
        "session id: S02\n"
        "file: /data/S02/a.nii.gz\n"
    )

    records = bio.read_list(str(path))

    assert [e["id"] for e in records] == ["S01", "S02"]
    assert records[0]["file"] == ["/data/S01/a.nii.gz", "/data/S01/b.nii.gz"]
    assert records[0]["roi"] == ["/data/S01/roi.nii.gz"]


def test_read_list_raises_on_a_missing_file(tmp_path):
    with pytest.raises(bio.BatchError):
        bio.read_list(str(tmp_path / "there-is-no.list"))


# -------------------------------------------------------------------- selection


def records(tmp_path):
    return bio.read_batch(write_batch(tmp_path))[0]


def test_select_sessions_returns_everything_by_default(tmp_path):
    assert len(bio.select_sessions(records(tmp_path))) == 3


def test_select_sessions_selects_by_id(tmp_path):
    selected = bio.select_sessions(records(tmp_path), sessions="S01,S03")

    assert selected.get_list_by_key("id") == "S01,S03"


def test_select_sessions_takes_any_separator(tmp_path):
    for spec in ["S01,S03", "S01 S03", "S01|S03", "S01, S03"]:
        assert bio.select_sessions(records(tmp_path), sessions=spec).get_list_by_key(
            "id"
        ) == "S01,S03"


def test_select_sessions_globs_the_ids(tmp_path):
    assert len(bio.select_sessions(records(tmp_path), sessions="S0*")) == 3
    assert len(bio.select_sessions(records(tmp_path), sessions="S0?")) == 3
    assert len(bio.select_sessions(records(tmp_path), sessions="S[01]*")) == 3

    # a glob, not an unanchored regex: S0 alone matches nothing
    assert len(bio.select_sessions(records(tmp_path), sessions="S0")) == 0


def test_select_sessions_filters_by_key(tmp_path):
    selected = bio.select_sessions(records(tmp_path), filter="group:patient")

    assert selected.get_list_by_key("id") == "S02,S03"


def test_select_sessions_filter_ors_and_ands(tmp_path):
    ored = bio.select_sessions(records(tmp_path), filter="group:control|task:motor")
    anded = bio.select_sessions(records(tmp_path), filter="group:patient&task:rest")

    assert ored.get_list_by_key("id") == "S01,S03"
    assert anded.get_list_by_key("id") == "S02"


def test_select_sessions_filter_values_are_globs(tmp_path):
    assert len(bio.select_sessions(records(tmp_path), filter="group:pat*")) == 2
    assert len(bio.select_sessions(records(tmp_path), filter="task:r?st")) == 2


def test_an_empty_filter_selects_everything(tmp_path):
    for empty in [None, "", "   "]:
        assert len(bio.select_sessions(records(tmp_path), filter=empty)) == 3


def test_a_filter_mixing_operators_is_an_error(tmp_path):
    with pytest.raises(bio.BatchError):
        bio.select_sessions(records(tmp_path), filter="group:control|task:rest&id:S01")


def test_a_malformed_filter_is_an_error(tmp_path):
    for bad in ["group", "group:", ":control", "group:control|task"]:
        with pytest.raises(bio.BatchError):
            bio.select_sessions(records(tmp_path), filter=bad)


def test_select_sessions_combines_the_selection_and_the_filter(tmp_path):
    selected = bio.select_sessions(
        records(tmp_path), sessions="S01,S02", filter="group:patient"
    )

    assert selected.get_list_by_key("id") == "S02"


def test_without_records_the_sessions_are_the_ids(tmp_path):
    assert bio.select_sessions([], sessions="S01,S02").get_list_by_key("id") == "S01,S02"


def test_without_records_a_sessions_folder_is_globbed(tmp_path):
    for session in ["S01", "S02", "S10"]:
        os.makedirs(tmp_path / session)

    selected = bio.select_sessions([], sessions="S0*", sessionsfolder=str(tmp_path))

    assert selected.get_list_by_key("id") == "S01,S02"


def test_the_source_records_are_not_modified(tmp_path):
    source = records(tmp_path)

    selected = bio.select_sessions(source, filter="group:control")
    selected[0]["group"] = "changed"

    assert source[0]["group"] == "control"


# ------------------------------------------------------- core.resolve_sessions


def test_resolve_sessions_returns_the_sessions_and_the_header(tmp_path):
    sessions, header = gc.resolve_sessions(batchfile=write_batch(tmp_path))

    assert sessions.get_list_by_key("id") == "S01,S02,S03"
    assert header["hcp_brainsize"] == "150"
    assert isinstance(sessions, gc.SessionList)


def test_resolve_sessions_selects_and_filters(tmp_path):
    batchfile = write_batch(tmp_path)

    assert (
        gc.resolve_sessions(batchfile=batchfile, sessions="S01,S02")[0].get_list_by_key(
            "id"
        )
        == "S01,S02"
    )
    assert (
        gc.resolve_sessions(batchfile=batchfile, filter="group:patient")[
            0
        ].get_list_by_key("id")
        == "S02,S03"
    )


def test_resolve_sessions_without_a_batch_file(tmp_path):
    sessions, header = gc.resolve_sessions(sessions="S01,S02")

    assert sessions.get_list_by_key("id") == "S01,S02"
    assert header == {}


def test_resolve_sessions_globs_a_sessions_folder(tmp_path):
    for session in ["S01", "S02", "S10"]:
        os.makedirs(tmp_path / session)

    sessions, header = gc.resolve_sessions(
        sessions="S0*", sessionsfolder=str(tmp_path)
    )

    assert sessions.get_list_by_key("id") == "S01,S02"
    assert header == {}


def test_resolve_sessions_reads_a_list_file(tmp_path):
    path = tmp_path / "sessions.list"
    path.write_text("session id: S01\nfile: /data/S01/a.nii.gz\n")

    sessions, header = gc.resolve_sessions(batchfile=str(path))

    assert sessions.get_list_by_key("id") == "S01"
    assert header == {}


def test_a_list_file_can_arrive_through_sessions(tmp_path):
    # a *.list file is a session specification, so --sessions is where it belongs;
    # with no batch file it is the source of the sessions and of their files
    path = tmp_path / "sessions.list"
    path.write_text(
        "session id: S01\nfile: /data/S01/a.nii.gz\nsession id: S02\nfile: /data/S02/a.nii.gz\n"
    )

    sessions, header = gc.resolve_sessions(sessions=str(path))

    assert sessions.get_list_by_key("id") == "S01,S02"
    assert sessions[0]["file"] == ["/data/S01/a.nii.gz"]
    assert header == {}


def test_a_list_file_through_sessions_selects_within_a_batch_file(tmp_path):
    batch = tmp_path / "batch.txt"
    batch.write_text(BATCH)
    path = tmp_path / "sessions.list"
    path.write_text("session id: S02\nfile: /data/S02/a.nii.gz\n")

    sessions, header = gc.resolve_sessions(batchfile=str(batch), sessions=str(path))

    assert sessions.get_list_by_key("id") == "S02"
    assert header != {}


def test_a_missing_batch_file_is_always_an_error(tmp_path):
    missing = str(tmp_path / "there-is-no-batch.txt")

    with pytest.raises(CommandFailed) as e:
        gc.resolve_sessions(batchfile=missing, sessions="S01,S02", command="import_bids")

    assert e.value.function == "import_bids"
    assert missing in " ".join(e.value.report)


def test_a_bad_filter_is_reported_as_a_command_failure(tmp_path):
    with pytest.raises(CommandFailed):
        gc.resolve_sessions(batchfile=write_batch(tmp_path), filter="group")


def test_get_sessions_list_is_gone():
    """Every caller takes a batch file and a session specification separately."""
    assert not hasattr(gc, "get_sessions_list")
