#!/usr/bin/env python
# encoding: utf-8

# SPDX-FileCopyrightText: 2026 QuNex development team <https://qunex.yale.edu/>
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""
``run_qc_summary`` compiles what a study already holds, and says what it cannot.

The command's contract is unusual for a processing command, and these tests are
that contract: a session that has not reached a processing stage is *reported*
rather than dropped or raised on, and only being unable to build the report the
command was asked for counts as a failure. So most of what is checked here is
what happens when something is not there.

The movement fixture is written in the format ``compute_bold_stats`` writes
today -- a QuNex provenance block, and in a ``.scrub`` the parameters the
scrubbing was computed with, ahead of the header. That is the shape that broke
``mov_stats.read_named``, and the committed ``test_data/mov_stats`` fixtures do
not have it: they begin at the header line, which is why all 22 tests over them
passed while ``create_stats_report`` was failing on every real run.

The ``.scrub`` also flags one frame that the ``.bstats`` traces alone would not
justify. That is deliberate: the frames this command reports are the frames
preprocessing excluded, read out of the ``.scrub`` file rather than
re-thresholded from the traces, and a fixture where the two agree cannot tell
the two apart.
"""

import csv
import importlib.abc
import json
import os
import sys

import pytest

import qx_utilities.processing.mov_stats as ms
import qx_utilities.processing.workflow.qc_summary_bold as qcb
import qx_utilities.processing.workflow.qc_summary_report as qcr
from qx_utilities.processing.workflow.run_qc_summary import (
    SESSION_COLUMNS,
    run_qc_summary,
)
from tests.utils import default_options


# ------------------------------------------------------------- the fixture ---

# what `general_compute_bold_stats` puts ahead of the header of both files
PROVENANCE = "# Generated by QuNex 1.5.0 on 2026-08-13_10.00.00\n#\n"

# and, for a `.scrub`, the parameters the scrubbing was computed with. These
# match the command's own defaults, which is what makes the flags readable as
# the pipeline's rather than as something the command asked for instead
SCRUB_PARAMETERS = (
    "# Parameters used\n"
    "# radius:   50\n"
    "# fdt:      0.50\n"
    "# dvarsmt:  3.00\n"
    "# dvarsmet: 1.50\n"
    "# after:    0\n"
    "# before:   0\n"
    "# reject:   udvarsme\n"
)

BSTATS_COLUMNS = ["frame", "n", "m", "var", "sd", "dvars", "dvarsm", "dvarsme", "fd"]
SCRUB_COLUMNS = ["frame"] + ms.CRITERIA + ["use"]

# the run the fixture describes: twelve frames, with peak displacement on
# frames 4 and 5 and a DVARSme spike on frame 9
FD = [0.0, 0.04, 0.03, 0.91, 0.77, 0.02, 0.05, 0.03, 0.04, 0.02, 0.03, 0.01]
DVARSME = [0.0, 0.9, 0.8, 1.1, 1.0, 0.9, 0.8, 1.0, 2.2, 0.9, 0.8, 0.9]

# what the `.bstats` traces above justify at the default thresholds, and so what
# a command that re-derived the flags would count
TRACE_BAD = {4, 5, 9}

# what the pipeline flagged, per criterion. Frame 11 is over the movement
# threshold and nothing in the `.bstats` traces says so: the pipeline's
# displacement comes from the movement parameters at the head radius, the
# `fd` column from the image statistics, and the two do not have to agree
# frame for frame. It is here so that reading the file and re-deriving from
# the traces give different answers, and the tests can tell which happened
SCRUB_FLAGS = {
    "mov": {4, 5, 11},
    "dvars": {9},
    "dvarsme": {9},
}
SCRUB_FLAGS["idvars"] = SCRUB_FLAGS["mov"] & SCRUB_FLAGS["dvars"]
SCRUB_FLAGS["idvarsme"] = SCRUB_FLAGS["mov"] & SCRUB_FLAGS["dvarsme"]
SCRUB_FLAGS["udvars"] = SCRUB_FLAGS["mov"] | SCRUB_FLAGS["dvars"]
SCRUB_FLAGS["udvarsme"] = SCRUB_FLAGS["mov"] | SCRUB_FLAGS["dvarsme"]

# the default `--mov_bad` is `udvarsme`, so this is what the command reports
SCRUB_BAD = SCRUB_FLAGS["udvarsme"]


def _table(path, columns, rows, pre, trailer):
    """One movement table, laid out the way ``general_write_table`` lays it out."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    lines = ["".join("%-10s" % name for name in columns).rstrip()]
    for row in rows:
        lines.append("".join("%-10g" % value for value in row).rstrip())
    lines += trailer
    with open(path, "w") as table:
        table.write(pre + "\n".join(lines) + "\n")


def _write_bstats(path, fd=FD, dvarsme=DVARSME):
    rows = [
        [frame, 434673, 15432.0, 1.614e08, 12704.6, value * 400, value * 2.6, value, motion]
        for frame, (motion, value) in enumerate(zip(fd, dvarsme), 1)
    ]
    _table(path, BSTATS_COLUMNS, rows, PROVENANCE,
           ["#max       434673     15476      1.6e+08    12725      880        5.72       2.2        0.91",
            "#mean      434673     15450      1.6e+08    12710      356        2.31       0.89       0.16"])


def _write_scrub(path, flags=SCRUB_FLAGS, frames=len(FD)):
    rows = []
    for frame in range(1, frames + 1):
        flagged = [int(frame in flags[name]) for name in ms.CRITERIA]
        # `reject` is `udvarsme`, so that is the column `use` is the inverse of
        rows.append([frame] + flagged + [int(frame not in flags["udvarsme"])])

    totals = [len(flags[name]) for name in ms.CRITERIA]
    totals.append(frames - len(flags["udvarsme"]))
    _table(path, SCRUB_COLUMNS, rows, PROVENANCE + SCRUB_PARAMETERS, [
        "#sum      " + "".join("%-9d" % total for total in totals),
        "#%        " + "".join("%-9.3g" % (100.0 * total / frames) for total in totals),
    ])


ASEG = """\
# Title Segmentation Statistics
# Measure BrainSeg, BrainSegVol, Brain Segmentation Volume, 1215432.000000, mm^3
# Measure EstimatedTotalIntraCranialVol, eTIV, Estimated Total Intracranial Volume, 1584321.000000, mm^3
# Measure SurfaceHoles, SurfaceHoles, Number of defect holes, 27.000000, unitless
"""

APARC = """\
# Table of FreeSurfer cortical parcellation anatomical statistics
# Measure Cortex, MeanThickness, Mean Thickness, 2.4531, mm
"""


def _session(sessionsfolder, sid, *, freesurfer=True, bolds=1, truncated=False):
    """
    A session on disk, with as much or as little of the pipeline behind it.

    Only the two stages that need no image data are ever written -- the
    FreeSurfer statistics tables and the BOLD movement files. Everything else
    is a stage the session has not reached, which is the case these tests are
    mostly about.
    """
    sinfo = {"id": sid, "hcp": os.path.join(sessionsfolder, sid, "hcp")}

    if freesurfer:
        stats = os.path.join(sinfo["hcp"], sid, "T1w", sid, "stats")
        os.makedirs(stats, exist_ok=True)
        with open(os.path.join(stats, "aseg.stats"), "w") as aseg:
            aseg.write(ASEG)
        for hemisphere in ("lh", "rh"):
            with open(os.path.join(stats, f"{hemisphere}.aparc.stats"), "w") as aparc:
                aparc.write(APARC)

    movement = os.path.join(sessionsfolder, sid, "images", "functional", "movement")
    for run in range(1, bolds + 1):
        sinfo[str(run)] = {"name": f"bold{run}", "task": "rest",
                           "filename": f"BOLD_{run}"}
        stats = os.path.join(movement, f"bold{run}.bstats")
        if truncated:
            # a file cut off mid-write: the header promises nine columns and
            # the rows carry four. This is what `np.genfromtxt` raises on, and
            # the run it belongs to is what that may cost -- not the study
            os.makedirs(movement, exist_ok=True)
            with open(stats, "w") as cut:
                cut.write(PROVENANCE + " ".join(BSTATS_COLUMNS) + "\n1 2 3 4\n")
            continue
        _write_bstats(stats)
        _write_scrub(os.path.join(movement, f"bold{run}.scrub"))

    return sinfo


def _options(sessionsfolder, **overrides):
    return default_options(sessionsfolder=str(sessionsfolder), **overrides)


def _tree(root):
    """Every file under `root`, with its size and mtime. Directories excluded."""
    found = {}
    for dirpath, _, filenames in os.walk(root):
        for name in filenames:
            path = os.path.join(dirpath, name)
            stat = os.stat(path)
            found[path] = (stat.st_size, stat.st_mtime_ns)
    return found


def _qcfolder(sessionsfolder):
    """The one run folder the command wrote under the study's QC folder."""
    qc = os.path.join(sessionsfolder, "QC")
    runs = sorted(name for name in os.listdir(qc) if name.startswith("qc_summary_"))
    assert len(runs) == 1, runs
    return os.path.join(qc, runs[0])


def _rows(path):
    with open(path, newline="") as tsv:
        return list(csv.DictReader(tsv, delimiter="\t"))


@pytest.fixture
def study(tmp_path):
    """A two session study: one with data behind it, one with none at all."""
    sessionsfolder = tmp_path / "sessions"
    sessionsfolder.mkdir()
    return [_session(str(sessionsfolder), "s01"),
            {"id": "s02"}], str(sessionsfolder)


# --------------------------------------------------------------- the dry run --


def test_dry_run_writes_nothing_and_names_what_it_would_write(study, tmp_path):
    sinfo, sessionsfolder = study
    options = _options(sessionsfolder, run="test")

    before = _tree(tmp_path)
    log = run_qc_summary(sinfo, options)
    assert _tree(tmp_path) == before

    named = [line.split("test, not written: ")[1].strip()
             for line in log.text.splitlines() if "test, not written: " in line]
    assert {os.path.basename(path) for path in named} == {
        "qc_summary.tsv", "qc_summary_bold.tsv",
        "qc_summary_bold_traces.json", "qc_summary_report.html"}
    assert all(path.startswith(os.path.join(sessionsfolder, "QC")) for path in named)

    # and the run's own folder, which it named and did not create. The study's
    # `QC` folder itself is not checked: `pc.get_session_folders` creates the
    # session skeleton whenever it resolves paths, for every processing command
    # in the tree, which is why `_tree` records files and not directories
    assert "test, not created" in log.text
    assert not os.path.isdir(os.path.dirname(named[0]))

    assert log.status[2] == 0


# --------------------------------------------------------- what is not there --


def test_a_session_missing_a_stage_is_reported_rather_than_dropped(study):
    sinfo, sessionsfolder = study
    log = run_qc_summary(sinfo, _options(sessionsfolder, qc_summary_report="no"))

    rows = {row["session"]: row for row in _rows(
        os.path.join(_qcfolder(sessionsfolder), "qc_summary.tsv"))}
    assert set(rows) == {"s01", "s02"}

    # s01 has been through recon-all and has BOLD data, and nothing else
    assert rows["s01"]["completeness"] == "2/5"
    assert rows["s01"]["stages_missing"] == "prefs,postfs,dwi"
    assert rows["s01"]["fs_surface_holes"] == "27.0"

    # no session in the study reached PreFreeSurfer, so its columns are not in
    # the table at all -- an empty column would say the same thing at the cost
    # of a screen's width of nothing
    assert "mni_brain_volume_ml" not in rows["s01"]

    # s02 carries no `hcp` at all, which is a normal state and not an error
    assert rows["s02"]["completeness"] == "0/5"
    assert rows["s02"]["stages_missing"] == "prefs,fs,postfs,bold,dwi"
    assert rows["s02"]["likely_failure_step"] == "Pipeline incomplete"

    assert "no HCP folder for s02" in log.text
    assert log.status[2] == 0


def test_a_truncated_bstats_costs_its_run_and_not_the_study(tmp_path):
    sessionsfolder = tmp_path / "sessions"
    sessionsfolder.mkdir()
    sinfo = [_session(str(sessionsfolder), "s01"),
             _session(str(sessionsfolder), "s02", truncated=True)]

    log = run_qc_summary(sinfo, _options(sessionsfolder, qc_summary_report="no"))

    runs = _rows(os.path.join(_qcfolder(str(sessionsfolder)), "qc_summary_bold.tsv"))
    assert [run["session"] for run in runs] == ["s01"]

    rows = {row["session"]: row for row in _rows(
        os.path.join(_qcfolder(str(sessionsfolder)), "qc_summary.tsv"))}
    assert rows["s02"]["bold_n"] == ""
    assert "could not read the statistics for bold1" in log.text

    # the run is lost, the session is still reported, and the study succeeds
    assert log.status[2] == 0


# ------------------------------------------------------- the scrubbing flags --


def test_the_bad_frames_are_the_ones_the_scrub_file_records(tmp_path):
    sessionsfolder = tmp_path / "sessions"
    sessionsfolder.mkdir()
    sinfo = [_session(str(sessionsfolder), "s01")]

    run_qc_summary(sinfo, _options(sessionsfolder, qc_summary_report="no"))

    qcfolder = _qcfolder(str(sessionsfolder))
    run = _rows(os.path.join(qcfolder, "qc_summary_bold.tsv"))[0]

    assert run["flags"] == "pipeline"
    assert int(run["n_bad"]) == len(SCRUB_BAD)
    assert int(run["frames_retained"]) == len(FD) - len(SCRUB_BAD)
    assert run["fdt"] == "0.5" and run["dvarsmet"] == "1.5"

    # and the traces carry the same mask, so the report plots what the table counts
    with open(os.path.join(qcfolder, "qc_summary_bold_traces.json")) as traces:
        trace = json.load(traces)["s01/bold1"]
    assert {frame for frame, bad in enumerate(trace["bad"], 1) if bad} == SCRUB_BAD


def test_an_explicit_threshold_recomputes_the_flags_and_says_so(tmp_path):
    sessionsfolder = tmp_path / "sessions"
    sessionsfolder.mkdir()
    sinfo = [_session(str(sessionsfolder), "s01")]

    # a threshold the run was not processed with is the one case the flags are
    # rebuilt from the traces, and the row has to say that they were
    run_qc_summary(sinfo, _options(sessionsfolder, mov_fd="0.7",
                                   qc_summary_report="no"))

    run = _rows(os.path.join(_qcfolder(str(sessionsfolder)),
                             "qc_summary_bold.tsv"))[0]
    assert run["flags"] == "recomputed"
    assert int(run["n_bad"]) == len(TRACE_BAD)
    assert run["fdt"] == "0.7"


# ------------------------------------------------------------- the tables ----


def test_the_tables_carry_the_declared_headers(study):
    sinfo, sessionsfolder = study
    run_qc_summary(sinfo, _options(sessionsfolder, qc_summary_report="no"))

    qcfolder = _qcfolder(sessionsfolder)
    with open(os.path.join(qcfolder, "qc_summary.tsv"), newline="") as tsv:
        header = next(csv.reader(tsv, delimiter="\t"))

    # a column no session in the study has a value for is left out entirely,
    # so the header is the declared order narrowed rather than reordered
    assert header[0] == "session"
    assert header == [name for name in SESSION_COLUMNS if name in header]
    for name in ("fs_surface_holes", "completeness", "stages_missing",
                 "likely_failure_step"):
        assert name in header

    with open(os.path.join(qcfolder, "qc_summary_bold.tsv"), newline="") as tsv:
        assert next(csv.reader(tsv, delimiter="\t")) == qcb.RUN_COLUMNS


# -------------------------------------------------------------- the report ---


SESSION_ROWS = [
    {"session": "s01", "fs_surface_holes": 27.0, "fs_mean_thickness": 2.45,
     "bold_n": 2, "bold_worstFD": 0.91, "likely_failure_step": "OK",
     "diagnosis_evidence": "", "completeness": "2/5", "stages_missing": "prefs"},
    {"session": "s02", "fs_surface_holes": 214.0, "fs_mean_thickness": 2.11,
     "bold_n": 1, "bold_worstFD": 2.4, "likely_failure_step": "FreeSurfer (recon quality)",
     "diagnosis_evidence": "surface holes high (214)", "completeness": "2/5",
     "stages_missing": "prefs"},
    {"session": "s03", "fs_surface_holes": 31.0, "fs_mean_thickness": 2.39,
     "bold_n": 2, "bold_worstFD": 0.4, "likely_failure_step": "OK",
     "diagnosis_evidence": "", "completeness": "2/5", "stages_missing": "prefs"},
]

RUN_ROWS = [
    {"session": "s01", "run": "bold1", "n_frames": 12, "fd_mean": 0.16,
     "fd_max": 0.91, "n_bad": 4, "pct_bad": 33.3, "criterion": "udvarsme",
     "flags": "pipeline"},
]


@pytest.fixture
def library(tmp_path, monkeypatch):
    """
    A ``qx_library`` the report can be built from, pointed at by ``QUNEXPATH``.

    CI checks the repository out with ``submodules: false`` and with no QuNex
    environment, so the real template is not there to be read and no test can
    assume it is. The stub carries the two placeholders the module substitutes
    into, which is the whole of the coupling between it and the page.
    """
    folder = tmp_path / "library" / "qx_library" / "data" / "scenes" / "qc"
    folder.mkdir(parents=True)
    (folder / qcr.TEMPLATE_NAME).write_text(
        "<html><script>/*PLOTLY*/</script>"
        "<script>const payload = /*DATA*/;</script></html>")
    (folder / qcr.PLOTLY_NAME).write_text("/* plotly stands in here */")
    monkeypatch.setenv("QUNEXPATH", str(tmp_path / "library"))
    return folder


@pytest.fixture
def no_pandas(monkeypatch):
    """
    Make ``import pandas`` and ``import scipy`` fail, as they do on the runner.

    ``.github/workflows/tests.yml`` installs neither, and dropping pandas from
    the report is one of the things this command was written for -- so the
    claim is worth holding to rather than trusting to the local environment,
    which has both.
    """
    blocked = ("pandas", "scipy")

    for name in list(sys.modules):
        if name.split(".")[0] in blocked:
            monkeypatch.delitem(sys.modules, name)

    class Absent(importlib.abc.MetaPathFinder):
        def find_spec(self, fullname, path=None, target=None):
            if fullname.split(".")[0] in blocked:
                raise ImportError(f"No module named '{fullname}'")
            return None

    monkeypatch.setattr(sys, "meta_path", [Absent()] + sys.meta_path)


def test_build_report_needs_no_pandas(tmp_path, library, no_pandas):
    html = qcr.build_report(SESSION_ROWS, RUN_ROWS, {"s01/bold1": {"fd": [0.1, 0.2]}},
                            _options(tmp_path / "sessions"))

    assert "/*DATA*/" not in html and "/*PLOTLY*/" not in html
    assert "plotly stands in here" in html

    payload = json.loads(html.split("const payload = ")[1].split(";</script>")[0])
    assert payload["subjects"] == ["s01", "s02", "s03"]
    assert "fs_surface_holes" in payload["metrics"]
    assert payload["stats"]["fs_surface_holes"]["median"] == 31.0
    assert payload["bold_runs"][0]["subject"] == "s01"
    assert payload["bold_traces"] == {"s01/bold1": {"fd": [0.1, 0.2]}}

    # `stages_missing` is the same for every session, so it carries nothing to
    # plot and the report says so rather than offering it as a parameter
    assert "stages_missing" not in payload["metrics"]


def test_a_missing_template_is_a_failure_and_is_named(study, tmp_path, monkeypatch):
    sinfo, sessionsfolder = study
    monkeypatch.setenv("QUNEXPATH", str(tmp_path / "empty"))

    log = run_qc_summary(sinfo, _options(sessionsfolder))

    assert log.status[2] == 1
    assert qcr.TEMPLATE_NAME in log.text
    assert "qx_library submodule" in log.text

    # the tables are what the command did manage, and they stay
    qcfolder = _qcfolder(sessionsfolder)
    assert os.path.isfile(os.path.join(qcfolder, "qc_summary.tsv"))
    assert not os.path.isfile(os.path.join(qcfolder, "qc_summary_report.html"))


def test_no_qunexpath_is_a_failure_that_says_what_to_do(study, monkeypatch):
    sinfo, sessionsfolder = study
    monkeypatch.delenv("QUNEXPATH", raising=False)

    log = run_qc_summary(sinfo, _options(sessionsfolder))

    assert log.status[2] == 1
    assert "QUNEXPATH is not set" in log.text
    assert "--qc_summary_report=no" in log.text
